# Copyright (c) 2026, dishsim project.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Every tunable of the v0 placement pipeline, in one place.

Values marked *measured* come from ``docs/joint_report.md`` (regenerated by
``scripts/00_inspect_scene.py``) or from a ``scripts/10_v0_scene.py --measure`` run; do not
eyeball-edit them. Frame convention everywhere: **robot-base frame, meters, Z-up, quaternions
XYZW** (world frame = robot-base frame shifted by ``ROBOT_BASE_POS_W``; the robot base spawns
with identity rotation, asserted at scene build).

This module must stay importable without Kit *and* without the planning venv (numpy only).
"""

import math
import os

from . import ASSETS_DIR

# ---------------------------------------------------------------------------------------------
# frame convention (asserted by scene.assert_frames and the collision-world manifest)
# ---------------------------------------------------------------------------------------------
FRAME_CONVENTION = {"frame": "robot_base", "units": "m", "up": "+z", "quat": "xyzw"}

# ---------------------------------------------------------------------------------------------
# scene layout (world frame; measured — docs/joint_report.md)
# ---------------------------------------------------------------------------------------------
ROBOT_BASE_POS_W = (0.0, 0.0, 0.25)
ROBOT_BASE_QUAT_W = (0.0, 0.0, 0.0, 1.0)
PEDESTAL_SIZE = (0.25, 0.25, 0.25)
PEDESTAL_POS_W = (0.0, 0.0, 0.125)
# dishwasher articulation-root (E_body_5) spawn pose: front face toward the robot, handle
# centered at x ~ 0.64 when the door is closed (measured RL placement, joint_report.md)
DISHWASHER_POS_W = (0.6498, 0.2423, 0.0)
DISHWASHER_QUAT_W = (0.0, 0.0, -0.70710678, 0.70710678)  # yaw -90 deg

ARM_JOINTS = [
    "shoulder_pan_joint",
    "shoulder_lift_joint",
    "elbow_joint",
    "wrist_1_joint",
    "wrist_2_joint",
    "wrist_3_joint",
]
HOME_Q = (0.0, -1.712, 1.712, -1.571, -1.571, 0.0)  # elbow-up home, faces +x (measured-stable)
UR5E_REACH_M = 0.85

# ---------------------------------------------------------------------------------------------
# static machine state (v0: door locked open, lower rack fully out)
# ---------------------------------------------------------------------------------------------
DOOR_OPEN_DEG = 90.0
DOOR_BAND_DEG = 5.0  # v0 USD clamps door limits to [open - band, open]
# The asset's effective mechanical stop is 89.05 deg (measured: the door rests there both under
# gravity and under +8 N*m in the joint_report door test, despite the authored 90 deg limit).
# Init at 89.0 so the settle transient is tiny; gravity presses the panel into the stop.
DOOR_INIT_RAD = math.radians(89.0)
DOOR_REST_DEG = 89.05  # measured rest angle at the stop
RACK_LOWER_EXT_M = -0.20  # PrismaticJoint_dishwasher_2_down: 0 = stowed, -0.2 = fully out
RACK_UPPER_EXT_M = 0.0  # upper rack stays stowed
RACK_JOINT_TARGETS = {
    "PrismaticJoint_dishwasher_2_down": RACK_LOWER_EXT_M,
    "PrismaticJoint_dishwasher_2_up": RACK_UPPER_EXT_M,
}

# ---------------------------------------------------------------------------------------------
# gripper (actuated between exactly two calibrated apertures: open at trial endpoints, grasp
# during all planned motion — matching the frozen-aperture FCL cluster)
# ---------------------------------------------------------------------------------------------
GRIPPER_JOINT = "finger_joint"  # 0 = open (85 mm), ~0.8 = closed (inverted vs Franka)
GRIPPER_APERTURE_OPEN_RAD = 0.0  # fully open — trial start and release
# Grasp aperture = theta_touch + delta, measured by `scripts/11_calibrate_grasp.py` (staircase
# ramp onto the welded mug: theta_touch is the first sustained pad contact, delta a small
# over-command chosen so the steady pad force lands mid-band; the finger drive's
# effort_limit_sim=10 caps the squeeze). Measured 2026-07-31 (PASS run, rim_z -0.020):
# theta_touch 0.055, steady pad force 5.14 N mean at this setting.
GRIPPER_APERTURE_GRASP_RAD: float | None = 0.058
# Mimic-consistent drive targets for the two stiff (k=10) `.*_inner_finger_joint` actuators:
# leaving their targets at 0 while finger_joint closes makes them fight the mimic constraint
# and contaminates the measured pad force. Signs are measured live by the calibration script
# (upstream gear-assembly pattern predicts left -1 / right +1; we freeze what the mimic
# actually settles to). None -> hold_targets falls back to target-follows-measured-position
# (zero spring torque, damping only). Measured 2026-07-31: mimic ratios -0.995 / +0.995.
GRIPPER_INNER_FINGER_SIGNS: dict[str, float] | None = {
    "left_inner_finger_joint": -1.0,
    "right_inner_finger_joint": 1.0,
}
GRIPPER_CLOSE_RAMP_STEPS = 90  # 1.5 s at SIM_DT — the on-camera close at trial start
GRIPPER_OPEN_RAMP_STEPS = 90  # the on-camera open before the weld releases

# ---------------------------------------------------------------------------------------------
# TCP frame (wrist_3_link -> TCP)
# ---------------------------------------------------------------------------------------------
# Measured live by `scripts/10_v0_scene.py --measure` (2026-07-29, PASS run): translation
# (0, 0.130, 0) — matches joint_report.md — and rotation (-0.5, -0.5, -0.5, 0.5) XYZW (an exact
# axis permutation; measured values deviated < 3e-8 from ideal and were snapped to it).
T_WRIST3_TCP_POS = (0.0, 0.130, 0.0)
T_WRIST3_TCP_QUAT: tuple[float, float, float, float] | None = (-0.5, -0.5, -0.5, 0.5)

# ---------------------------------------------------------------------------------------------
# carried object + grasp (defined ONCE, used by scene weld, FK attachment, goal generation)
# ---------------------------------------------------------------------------------------------
# YCB 029_plate does NOT exist in the Isaac 6.0 S3 bucket (HTTP 404, checked 2026-07-29), so the
# mug is the v0 stand-in, as the project brief allows.
OBJECT_NAME = "025_mug"
OBJECT_USD = os.path.join(ASSETS_DIR, "props", "025_mug_physics.usd")
OBJECT_MASS_KG = 0.118
# Measured from the mesh (2026-07-29): the "Axis_Aligned" asset lies ON ITS SIDE — the mug AXIS
# runs along OBJECT +Y (opening/rim at y = +0.0407, closed bottom at y = -0.0407), the handle
# points along +X, and the body circle in the xz-plane is centered at (x, z) = (-0.0110, 0.0)
# with outer radius 0.0399. Bbox: +-(0.0585, 0.0407, 0.0465), origin at bbox center.
OBJECT_BBOX_HALF = (0.0585, 0.0407, 0.0465)
OBJECT_AXIS_OBJ = (0.0, 1.0, 0.0)  # mug "up" (bottom -> opening) in the object frame
OBJECT_BODY_CENTER_XZ = (-0.0110, 0.0)
OBJECT_RIM_RADIUS_M = 0.0399
OBJECT_HEIGHT_M = 0.0813

# Carry pose ("grasp" transform): the mug rides UPRIGHT in a calibrated contact pinch — its
# rim band between the inner-finger pads, handle on the jaw-free axis, the hidden wrist weld
# still carrying the load. GRASP_RIM_TCP_Z_M places the rim plane along tool z relative to the
# TCP (positive = beyond the TCP, away from the wrist) so the pad contact patch presses the
# outer wall PAD_ENGAGEMENT_M below the rim edge. Measured by `scripts/11_calibrate_grasp.py`
# from the live pad map — do not eyeball.
# Historical (clearance-carry era, kept for the record): closing to 0.78 rad (jaw ~ a few mm)
# onto the ~80 mm mug drove the jaw sweep through the wall — measured 155-420 N pads-on-rim,
# 263 N with the rim 30 mm below the TCP (closed fingertips arc ~50+ mm past the TCP). The v0
# answer was to hang the mug 85 mm below the TCP, beyond any fingertip reach (0 N by
# construction). The pinch regime is different: the jaws stop AT the mug surface
# (jaw ~ 79.8 mm, theta ~ 0.05-0.15 rad), so the sweep never drives through the wall and the
# pad force is bounded by the calibrated band below.
# Derivation:
#   R: z_tcp = -y_obj (upright carry, opening toward the gripper), x_tcp = +x_obj  == Rx(-90)
#   t: rim-center axis point (-0.011, 0.0407, 0)_obj maps to (0, 0, GRASP_RIM_TCP_Z_M)_tcp
# Measured 2026-07-31 (scripts/11_calibrate_grasp.py PASS: zero contact at open, band held
# at hold, weld error 1.3 mm under load, forces vanish on open).
GRASP_RIM_TCP_Z_M: float | None = -0.0200
PAD_ENGAGEMENT_M = 0.012  # pad contact-patch center below the rim edge (design choice)
GRASP_TCP_OBJ_POS: tuple[float, float, float] | None = (
    None if GRASP_RIM_TCP_Z_M is None else (0.011, 0.0, GRASP_RIM_TCP_Z_M + 0.0407)
)
GRASP_TCP_OBJ_QUAT = (-0.70710678, 0.0, 0.0, 0.70710678)  # Rx(-90 deg), XYZW

# ---------------------------------------------------------------------------------------------
# grip contact gates (calibrated by scripts/11_calibrate_grasp.py, used by Phases C/D/F)
# ---------------------------------------------------------------------------------------------
# The object_contact sensor's filter list resolves per-partner forces; the two inner-finger
# pads are the only bodies allowed (required, in fact) to touch the carried mug while gripping.
GRIP_PAD_BODIES = ("left_inner_finger", "right_inner_finger")
# Steady per-pad pinch-force band [N] while holding still (frozen 2026-07-31 from the
# calibration force-vs-theta curve: steady 5.14 N mean, per-pad [2.47, 7.82] N — the mild
# asymmetry is the handle-side mass/gearing bias; band = steady/3 .. 3x steady).
GRIP_FORCE_MIN_N = 1.7
GRIP_FORCE_MAX_N = 15.4
# Dynamic per-pad allowance [N] during arm motion (frozen 2026-07-31: 10_v0_scene wiggle
# peak 8.03 N at +-0.25 rad wrist wiggle, x1.5 margin).
GRIP_FORCE_EXEC_MAX_N = 12.0
RETRACT_DIST_M = 0.08  # post-release tool-axis retract before the final evaluation window
# The placed mug settles up to ~6 mm off the release point while the withdrawing jaws have
# only ~2.6 mm/side clearance — a light brush during retract is physically expected (as in
# real loading). Below this, contact is recorded as a graze and the trial is judged by the
# final evaluation window; at or above it, the retract failed outright.
RETRACT_GRAZE_MAX_N = 2.0

# ---------------------------------------------------------------------------------------------
# cameras (world frame; FIXED across all phases so shots are comparable)
# ---------------------------------------------------------------------------------------------
CAMERA_HW = (720, 1280)
CAMERA_FPS = 30
CAMERAS = {
    # eye, target
    "front": ((-0.40, -0.80, 0.60), (0.60, 0.00, 0.15)),  # looking into the dishwasher opening
    "top": ((0.50, 0.01, 1.70), (0.50, 0.00, 0.10)),  # straight down over the extended rack
    "iso": ((-0.50, 1.10, 0.90), (0.50, 0.05, 0.22)),  # 3/4 view onto the opening, robot at right
}

# ---------------------------------------------------------------------------------------------
# Phase D — collision world
# ---------------------------------------------------------------------------------------------
CACHE_DIR = os.path.join(ASSETS_DIR, "cache")
COLLISION_MARGIN_M = 0.005  # hull inflation: the conservative-bias knob for FCL-vs-Isaac parity
# CoACD parameters per body (fallback key "default"); threshold is the concavity tolerance —
# lower = finer decomposition. Rack quality is a *feasibility* parameter: too coarse falsely
# closes the tine gaps and every placement reads "in collision".
COACD = {
    "default": {"threshold": 0.05, "max_convex_hull": 32},
    "E_shelf_1_04": {"threshold": 0.02, "max_convex_hull": 128},  # lower rack: keep tine gaps open
    "E_shelf_03": {"threshold": 0.03, "max_convex_hull": 96},
    "object": {"threshold": 0.03, "max_convex_hull": 32},  # keep the mug cavity open
}
CONTACT_FORCE_THRESH_N = 0.1  # Isaac ground-truth contact threshold for the parity check
# The robot base sits ON the pedestal by construction (permanent touching contact) and is
# bolted to the world — it can never produce a *new* collision. Excluded from both the Isaac
# ground truth and the FCL world checks, keeping the two sides mirror images.
PARITY_BODY_EXCLUDE = ["base_link"]
WORLD_CHECK_EXCLUDE = ["base_link"]

# ---------------------------------------------------------------------------------------------
# Phase E — placement goals
# ---------------------------------------------------------------------------------------------
SLOT_TOL_LATERAL_M = 0.015
SLOT_TOL_TILT_DEG = 10.0
GOAL_POSE_SAMPLES_PER_SLOT = 64
SETTLE_STEPS = 300  # success criterion: pose holds for this many physics steps after release
# Slot derivation (the ArtVIP lower rack is a shallow WIRE BASKET, not a plate-tine rack — the
# mug STANDS on the wire floor; a "slot" is a standing position on a grid). Slot centers form
# an overlapping candidate grid (one object placed per trial), spanning the basket from the
# protruding front to the deep interior — rear-slot infeasibility is expected signal.
SLOT_RIM_INSET_M = 0.055  # keep the mug footprint away from the basket rim walls
SLOT_GRID_PITCH_M = 0.06  # candidate-center spacing (overlap allowed)
RELEASE_HOVER_M = 0.012  # goal poses hover the object above the wire floor (> collision margin,
#                          small enough that the release drop is a non-event)

# ---------------------------------------------------------------------------------------------
# Phase F — planning + execution
# ---------------------------------------------------------------------------------------------
PLAN_TIME_BUDGET_S = 5.0
PLAN_RRT_RANGE_RAD = 0.8  # RRT-Connect extension step; auto-range is too timid in the clutter
GOALS_PER_PLAN = 64  # random goal-set subset handed to OMPL per trial
# planning bounds: full joint limits minus a small margin (config-tunable; tighten if RRT
# wanders into pointless windups)
PLAN_JOINT_BOUNDS_MARGIN_RAD = 0.05
PLAN_VALIDITY_RESOLUTION_RAD = 0.015
EXEC_JOINT_SPEED_RAD_S = 0.5  # constant joint-speed cap for time parameterization
SIM_DT = 1.0 / 60.0
