# Copyright (c) 2026, dishsim project.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Every tunable of the v0 placement pipeline, in one place.

Values marked *measured* come from ``docs/joint_report.md`` (regenerated by
``scripts/setup/inspect_scene.py``) or from a ``scripts/setup/check_scene.py --measure`` run; do not
eyeball-edit them. Frame convention everywhere: **robot-base frame, meters, Z-up, quaternions
XYZW** (world frame = robot-base frame shifted by ``ROBOT_BASE_POS_W``; the robot base spawns
with identity rotation, asserted at scene build).

This module must stay importable without Kit *and* without the planning venv (numpy only).
"""

import contextlib
import math
import os

from . import ASSETS_DIR, PROJECT_ROOT

# ---------------------------------------------------------------------------------------------
# frame convention (asserted by scene.assert_frames and the collision-world manifest)
# ---------------------------------------------------------------------------------------------
FRAME_CONVENTION = {"frame": "robot_base", "units": "m", "up": "+z", "quat": "xyzw"}

# ---------------------------------------------------------------------------------------------
# scene layout (world frame; measured — docs/joint_report.md)
# ---------------------------------------------------------------------------------------------
ROBOT_BASE_POS_W = (0.0, 0.0, 0.25)
ROBOT_BASE_QUAT_W = (0.0, 0.0, 0.0, 1.0)
PEDESTAL_SIZE = (0.25, 0.25, 0.25)
PEDESTAL_POS_W = (0.0, 0.0, 0.125)
# dishwasher articulation-root (E_body_5) spawn pose: front face toward the robot, handle
# centered at x ~ 0.64 when the door is closed (measured RL placement, joint_report.md)
DISHWASHER_POS_W = (0.6498, 0.2423, 0.0)
DISHWASHER_QUAT_W = (0.0, 0.0, -0.70710678, 0.70710678)  # yaw -90 deg

ARM_JOINTS = [
    "shoulder_pan_joint",
    "shoulder_lift_joint",
    "elbow_joint",
    "wrist_1_joint",
    "wrist_2_joint",
    "wrist_3_joint",
]
HOME_Q = (0.0, -1.712, 1.712, -1.571, -1.571, 0.0)  # elbow-up home, faces +x (measured-stable)
UR5E_REACH_M = 0.85

# ---------------------------------------------------------------------------------------------
# static machine state (v0: door locked open, lower rack fully out)
# ---------------------------------------------------------------------------------------------
DOOR_OPEN_DEG = 90.0
DOOR_BAND_DEG = 5.0  # v0 USD clamps door limits to [open - band, open]
# The asset's effective mechanical stop is 89.05 deg (measured: the door rests there both under
# gravity and under +8 N*m in the joint_report door test, despite the authored 90 deg limit).
# Init at 89.0 so the settle transient is tiny; gravity presses the panel into the stop.
DOOR_INIT_RAD = math.radians(89.0)
DOOR_REST_DEG = 89.05  # measured rest angle at the stop
RACK_LOWER_EXT_M = -0.20  # PrismaticJoint_dishwasher_2_down: 0 = stowed, -0.2 = fully out
RACK_UPPER_EXT_M = -0.20  # baseline both_out: both racks fully extended
RACK_JOINT_TARGETS = {
    "PrismaticJoint_dishwasher_2_down": RACK_LOWER_EXT_M,
    "PrismaticJoint_dishwasher_2_up": RACK_UPPER_EXT_M,
}
#: Prismatic travel limits shared by both rack joints [m] (from the USD; docs/joint_report.md).
#: 0 = stowed, -0.20 = fully extended. The racks are independently articulated.
RACK_TRAVEL_LIMITS_M = (-0.20, 0.0)

# Rack-state scenarios — exactly the two real robot-facing INITIAL states (user-mandated).
# The dishwasher itself is unmodified (no rack raise): instead the robot does what a human
# does — it first RECONFIGURES the racks (rack_action: drive-synchronized pull/push on the
# named prismatic joint while the gripper visibly engages the rack's front handle), which
# brings BOTH scenarios to the same placement state (lower rack out, upper rack in — the
# geometry the placement pipeline is validated on), then picks the mug off the countertop
# and places it. "both_out" is the baseline (legacy assets/cache/, media/<phase>).
SCENARIOS = {
    "both_out": {  # both racks fully extended -> push the UPPER rack in, place into the lower
        "rack_lower_m": -0.20,
        "rack_upper_m": -0.20,
        "min_feasible_slots": 2,  # v3: the cutlery basket eats the x=0.2432 slot columns
        "rack_action": {
            "joint": "PrismaticJoint_dishwasher_2_up",
            "body": "E_shelf_03",
            "to": 0.0,
            "mode": "push",
        },
    },
    "both_in": {  # both racks fully retracted -> pull the LOWER rack out, place into it
        "rack_lower_m": 0.0,
        "rack_upper_m": 0.0,
        "min_feasible_slots": 2,  # v3: the cutlery basket eats the x=0.2432 slot columns
        "rack_action": {
            "joint": "PrismaticJoint_dishwasher_2_down",
            "body": "E_shelf_1_04",
            "to": -0.20,
            "mode": "pull",
        },
    },
}
SCENARIO_NAME = "both_out"  # active scenario; switch via apply_scenario() BEFORE scene imports

# The shared post-rack-action machine state every trial places in (lower out, upper in).
# Not a user-facing scenario — an internal state name usable with apply_scenario() and the
# cache/goal scripts (12-15) so pick/place planning has its own validated collision world.
PLACEMENT_STATE = "placement"
INTERNAL_STATES = {
    PLACEMENT_STATE: {"rack_lower_m": -0.20, "rack_upper_m": 0.0, "min_feasible_slots": 2},
    # Both racks extended, no rack action: the loading state for the REAR plate bank. The
    # ArtVIP rack travel (0.2 m) is smaller than the rack depth (0.287 m), so the rear
    # ~90 mm — the entire tine bank — never leaves the machine mouth: with the upper rack
    # stowed, its front rail sits directly above the bank and no collision-free insertion
    # exists (measured: 0/11 feasible plate slots in the `placement` state). Pulling the
    # upper rack out clears the airspace — exactly what a human does.
    "placement_open": {"rack_lower_m": -0.20, "rack_upper_m": -0.20, "min_feasible_slots": 2},
}


def apply_scenario(name: str) -> None:
    """Activate a rack-state scenario (or internal machine state) by rewriting the rack
    targets in place.

    Must run before importing :mod:`dishsim.robots`/:mod:`dishsim.scene` (they bind rack
    values and the derived-USD path at import time). ``geometry.config_hash`` reads these
    attributes at call time, so per-state caches invalidate correctly.

    Args:
        name: Key into :data:`SCENARIOS` or :data:`INTERNAL_STATES` (e.g. ``"placement"``).
    """
    global RACK_LOWER_EXT_M, RACK_UPPER_EXT_M, RACK_JOINT_TARGETS, SCENARIO_NAME
    states = {**SCENARIOS, **INTERNAL_STATES}
    if name not in states:
        raise ValueError(f"unknown scenario {name!r} (choices: {sorted(states)})")
    sc = states[name]
    RACK_LOWER_EXT_M = sc["rack_lower_m"]
    RACK_UPPER_EXT_M = sc["rack_upper_m"]
    RACK_JOINT_TARGETS = {
        "PrismaticJoint_dishwasher_2_down": RACK_LOWER_EXT_M,
        "PrismaticJoint_dishwasher_2_up": RACK_UPPER_EXT_M,
    }
    SCENARIO_NAME = name


def resolve_rack_state(spec=None, *, tol_m: float = 1e-6) -> str:
    """Resolve a rack-state spec to a NAMED state, or fail with how to create one.

    Accepts either a state name or explicit per-rack extensions::

        resolve_rack_state("placement")
        resolve_rack_state({"lower_m": -0.20, "upper_m": 0.0})

    Extensions cannot be free-form. :func:`dishsim.geometry.config_hash` includes the rack
    drive targets, and :func:`scenario_cache_dir` keys the collision cache by state *name* — so
    an unnamed combination has no cache directory, and pointing it at someone else's directory
    fails the staleness check. Rather than let that surface later as a confusing
    "cache is stale", this resolves up front and, when there is no match, says exactly what to
    add and which commands bake it.

    Args:
        spec: State name, or ``{"lower_m": float, "upper_m": float}``. Defaults to
            ``TASK["rack_state"]``.
        tol_m: Tolerance when matching extensions against a named state [m].

    Returns:
        The matching state name.

    Raises:
        ValueError: On an unknown name, a malformed spec, or an extension outside the joint
            limits.
        RuntimeError: When the extensions are valid but no named state carries them.
    """
    spec = TASK["rack_state"] if spec is None else spec
    states = {**SCENARIOS, **INTERNAL_STATES}
    if isinstance(spec, str):
        if spec not in states:
            raise ValueError(f"unknown rack state {spec!r} (choices: {sorted(states)})")
        return spec
    if not isinstance(spec, dict) or {"lower_m", "upper_m"} - set(spec):
        raise ValueError(
            f"rack_state must be a state name or {{'lower_m': float, 'upper_m': float}}, got {spec!r}"
        )
    lower, upper = float(spec["lower_m"]), float(spec["upper_m"])
    for label, value in (("lower_m", lower), ("upper_m", upper)):
        if not (RACK_TRAVEL_LIMITS_M[0] - tol_m <= value <= RACK_TRAVEL_LIMITS_M[1] + tol_m):
            raise ValueError(
                f"rack_state {label}={value} is outside the prismatic joint limits "
                f"{RACK_TRAVEL_LIMITS_M} (0 = stowed, -0.20 = fully out)"
            )
    # Match INTERNAL_STATES first. Extensions do not identify a state uniquely — `both_out` and
    # `placement_open` are both (-0.20, -0.20) and even share a config_hash, since the hash
    # covers the rack TARGETS and only the directory name separates them. The internal states
    # are the ones a multi-object episode can actually use (the scenarios carry a rack_action,
    # which the runner rejects), so they win; an ambiguity *within* a tier is a genuine
    # config problem and is reported rather than silently resolved.
    for tier, tier_states in (("INTERNAL_STATES", INTERNAL_STATES), ("SCENARIOS", SCENARIOS)):
        hits = [n for n, sc in tier_states.items()
                if abs(sc["rack_lower_m"] - lower) <= tol_m
                and abs(sc["rack_upper_m"] - upper) <= tol_m]
        if len(hits) > 1:
            raise RuntimeError(
                f"lower_m={lower}, upper_m={upper} matches several {tier} entries {sorted(hits)} "
                f"— name the one you mean instead of giving extensions"
            )
        if hits:
            return hits[0]
    known = ", ".join(f"{n} (lower {s['rack_lower_m']}, upper {s['rack_upper_m']})"
                      for n, s in sorted(states.items()))
    raise RuntimeError(
        f"no named machine state has lower_m={lower}, upper_m={upper}. Rack extensions are part "
        f"of the collision-cache hash, so a new combination needs its caches baked before it can "
        f"be used.\n"
        f"  known states: {known}\n"
        f"  to add one:   add an INTERNAL_STATES entry to src/dishsim/config.py, e.g.\n"
        f'                  "my_state": {{"rack_lower_m": {lower}, "rack_upper_m": {upper}, '
        f'"min_feasible_slots": 2}},\n'
        f"                then bake it for the classes you need:\n"
        f"                  scripts/setup/build_state.py --state my_state --classes mug,cup,tumbler"
    )


def state_params(name: str | None = None) -> dict:
    """Parameters of a scenario or internal machine state (e.g. Phase-E gates)."""
    name = name or SCENARIO_NAME
    return {**SCENARIOS, **INTERNAL_STATES}[name]


def scenario_cache_dir(name: str | None = None, object_name: str | None = None) -> str:
    """Collision-cache root for a scenario + a carried object.

    The mug keeps the legacy layout (baseline ``assets/cache/``, other states under
    ``assets/cache/scenarios/<state>``) so the validated v0 caches stay byte-stable; every
    other object gets ``assets/cache/objects/<object>/<state>``. CoACD piece dirs are
    content-addressed under the baseline root, so rack/shell decompositions are shared.

    Args:
        name: Scenario/state name; defaults to the active scenario.
        object_name: Object class; defaults to the active object. Passing it explicitly lets a
            multi-object episode read several classes' caches without calling
            :func:`set_active_object` — which rewrites module globals and would make the
            grasp/geometry view depend on call order.
    """
    name = name or SCENARIO_NAME
    obj = object_name or ACTIVE_OBJECT
    if obj != "mug":
        return os.path.join(ASSETS_DIR, "cache", "objects", obj, name)
    if name == "both_out":
        return CACHE_DIR
    return os.path.join(ASSETS_DIR, "cache", "scenarios", name)


def scenario_media_dir(phase: str, name: str | None = None) -> str:
    """Media dir for a phase under the active scenario (baseline keeps ``media/<phase>``)."""
    name = name or SCENARIO_NAME
    base = os.path.join(PROJECT_ROOT, "media", phase)
    return base if name == "both_out" else os.path.join(base, name)

# ---------------------------------------------------------------------------------------------
# gripper (actuated between exactly two calibrated apertures: open at trial endpoints, grasp
# during all planned motion — matching the frozen-aperture FCL cluster)
# ---------------------------------------------------------------------------------------------
GRIPPER_JOINT = "finger_joint"  # 0 = open (85 mm), ~0.8 = closed (inverted vs Franka)
GRIPPER_APERTURE_OPEN_RAD = 0.0  # fully open — trial start and release

#: Grasp families with no calibrated countertop pick. Measured, not stylistic: these contact the
#: pads one-sided, and closing on a free-lying object drags it (a 30 g fork travels ~21 mm during
#: the close, against a 5 mm weld gate). The single-object runner spawns them already welded at
#: the carry pose; an episode acquires them by snapping to the carry transform mid-run. Either
#: way it is NOT a pick, and the records label it so.
WELD_ACQUIRE_FAMILIES = ("edge_pinch", "rim_edge", "handle_pinch")
# Grasp aperture = theta_touch + delta, measured by `scripts/setup/calibrate_grasp.py` (staircase
# ramp onto the welded mug: theta_touch is the first sustained pad contact, delta a small
# over-command chosen so the steady pad force lands mid-band; the finger drive's
# effort_limit_sim=10 caps the squeeze). Measured 2026-07-31 (PASS run, rim_z -0.020):
# theta_touch 0.055, steady pad force 5.14 N mean at this setting.
GRIPPER_APERTURE_GRASP_RAD: float | None = 0.058
# Mimic-consistent drive targets for the two stiff (k=10) `.*_inner_finger_joint` actuators:
# leaving their targets at 0 while finger_joint closes makes them fight the mimic constraint
# and contaminates the measured pad force. Signs are measured live by the calibration script
# (upstream gear-assembly pattern predicts left -1 / right +1; we freeze what the mimic
# actually settles to). None -> hold_targets falls back to target-follows-measured-position
# (zero spring torque, damping only). Measured 2026-07-31: mimic ratios -0.995 / +0.995.
GRIPPER_INNER_FINGER_SIGNS: dict[str, float] | None = {
    "left_inner_finger_joint": -1.0,
    "right_inner_finger_joint": 1.0,
}
GRIPPER_CLOSE_RAMP_STEPS = 90  # 1.5 s at SIM_DT — the on-camera close at trial start
GRIPPER_OPEN_RAMP_STEPS = 90  # the on-camera open before the weld releases

# ---------------------------------------------------------------------------------------------
# TCP frame (wrist_3_link -> TCP)
# ---------------------------------------------------------------------------------------------
# Measured live by `scripts/setup/check_scene.py --measure` (2026-07-29, PASS run): translation
# (0, 0.130, 0) — matches joint_report.md — and rotation (-0.5, -0.5, -0.5, 0.5) XYZW (an exact
# axis permutation; measured values deviated < 3e-8 from ideal and were snapped to it).
T_WRIST3_TCP_POS = (0.0, 0.130, 0.0)
T_WRIST3_TCP_QUAT: tuple[float, float, float, float] | None = (-0.5, -0.5, -0.5, 0.5)

# ---------------------------------------------------------------------------------------------
# carried object + grasp (defined ONCE, used by scene weld, FK attachment, goal generation)
# ---------------------------------------------------------------------------------------------
# YCB 029_plate does NOT exist in the Isaac 6.0 S3 bucket (HTTP 404, checked 2026-07-29), so the
# mug is the v0 stand-in, as the project brief allows.
OBJECT_NAME = "025_mug"
OBJECT_USD = os.path.join(ASSETS_DIR, "props", "025_mug_physics.usd")
OBJECT_MASS_KG = 0.118
# Measured from the mesh (2026-07-29): the "Axis_Aligned" asset lies ON ITS SIDE — the mug AXIS
# runs along OBJECT +Y (opening/rim at y = +0.0407, closed bottom at y = -0.0407), the handle
# points along +X, and the body circle in the xz-plane is centered at (x, z) = (-0.0110, 0.0)
# with outer radius 0.0399. Bbox: +-(0.0585, 0.0407, 0.0465), origin at bbox center.
OBJECT_BBOX_HALF = (0.0585, 0.0407, 0.0465)
OBJECT_AXIS_OBJ = (0.0, 1.0, 0.0)  # mug "up" (bottom -> opening) in the object frame
OBJECT_BODY_CENTER_XZ = (-0.0110, 0.0)
OBJECT_RIM_RADIUS_M = 0.0399
OBJECT_HEIGHT_M = 0.0813

# Carry pose ("grasp" transform): the mug rides UPRIGHT in a calibrated contact pinch — its
# rim band between the inner-finger pads, handle on the jaw-free axis, the hidden wrist weld
# still carrying the load. GRASP_RIM_TCP_Z_M places the rim plane along tool z relative to the
# TCP (positive = beyond the TCP, away from the wrist) so the pad contact patch presses the
# outer wall PAD_ENGAGEMENT_M below the rim edge. Measured by `scripts/setup/calibrate_grasp.py`
# from the live pad map — do not eyeball.
# Historical (clearance-carry era, kept for the record): closing to 0.78 rad (jaw ~ a few mm)
# onto the ~80 mm mug drove the jaw sweep through the wall — measured 155-420 N pads-on-rim,
# 263 N with the rim 30 mm below the TCP (closed fingertips arc ~50+ mm past the TCP). The v0
# answer was to hang the mug 85 mm below the TCP, beyond any fingertip reach (0 N by
# construction). The pinch regime is different: the jaws stop AT the mug surface
# (jaw ~ 79.8 mm, theta ~ 0.05-0.15 rad), so the sweep never drives through the wall and the
# pad force is bounded by the calibrated band below.
# Derivation:
#   R: z_tcp = -y_obj (upright carry, opening toward the gripper), x_tcp = +x_obj  == Rx(-90)
#   t: rim-center axis point (-0.011, 0.0407, 0)_obj maps to (0, 0, GRASP_RIM_TCP_Z_M)_tcp
# Measured 2026-07-31 (scripts/setup/calibrate_grasp.py PASS: zero contact at open, band held
# at hold, weld error 1.3 mm under load, forces vanish on open).
GRASP_RIM_TCP_Z_M: float | None = -0.0200
PAD_ENGAGEMENT_M = 0.012  # pad contact-patch center below the rim edge (design choice)
GRASP_TCP_OBJ_POS: tuple[float, float, float] | None = (
    None if GRASP_RIM_TCP_Z_M is None else (0.011, 0.0, GRASP_RIM_TCP_Z_M + 0.0407)
)
GRASP_TCP_OBJ_QUAT = (-0.70710678, 0.0, 0.0, 0.70710678)  # Rx(-90 deg), XYZW

# ---------------------------------------------------------------------------------------------
# grip contact gates (calibrated by scripts/setup/calibrate_grasp.py, used by Phases C/D/F)
# ---------------------------------------------------------------------------------------------
# The object_contact sensor's filter list resolves per-partner forces; the two inner-finger
# pads are the only bodies allowed (required, in fact) to touch the carried mug while gripping.
GRIP_PAD_BODIES = ("left_inner_finger", "right_inner_finger")
# Steady per-pad pinch-force band [N] while holding still (frozen 2026-07-31 from the
# calibration force-vs-theta curve: steady 5.14 N mean, per-pad [2.47, 7.82] N — the mild
# asymmetry is the handle-side mass/gearing bias; band = steady/3 .. 3x steady).
GRIP_FORCE_MIN_N = 1.7
GRIP_FORCE_MAX_N = 15.4
# Dynamic per-pad allowance [N] during arm motion (frozen 2026-07-31: check_scene wiggle
# peak 8.03 N at +-0.25 rad wrist wiggle, x1.5 margin).
GRIP_FORCE_EXEC_MAX_N = 12.0
RETRACT_DIST_M = 0.08  # post-release tool-axis retract before the final evaluation window
# The placed mug settles up to ~6 mm off the release point while the withdrawing jaws have
# only ~2.6 mm/side clearance — a light brush during retract is physically expected (as in
# real loading). Below this, contact is recorded as a graze and the trial is judged by the
# final evaluation window; at or above it, the retract failed outright.
RETRACT_GRAZE_MAX_N = 2.0

# ---------------------------------------------------------------------------------------------
# cameras (world frame; FIXED across all phases so shots are comparable)
# ---------------------------------------------------------------------------------------------
CAMERA_HW = (720, 1280)
CAMERA_FPS = 30
CAMERAS = {
    # eye, target
    "front": ((-0.40, -0.80, 0.60), (0.60, 0.00, 0.15)),  # looking into the dishwasher opening
    "top": ((0.50, 0.01, 1.70), (0.50, 0.00, 0.10)),  # straight down over the extended rack
    "iso": ((-0.50, 1.10, 0.90), (0.50, 0.05, 0.22)),  # 3/4 view onto the opening, robot at right
}

# Per-camera lens. These used to be hardcoded in media.CameraRig, which is why no view could be
# widened without moving the eye — and why the episode video cropped the countertop out.
#
# The VERTICAL field of view is the binding constraint, not the horizontal one: the frame is
# 16:9 and `vertical_aperture` defaults to `horizontal_aperture * height/width`, so
#
#     focal 24 mm -> hFOV 47.2 deg, vFOV 27.6 deg
#
# Fitting the whole scene (a 1.01 m bounding sphere over robot + counter + machine + open door +
# extended racks) then needs the eye 4.24 m out at 24 mm — far enough that a 63 mm cup is
# unreadable. Widening the lens instead keeps the shot close: at 15 mm (vFOV 42.9 deg) the same
# sphere fits from 2.76 m.
CAMERA_LENS_DEFAULT = {"focal_length": 24.0, "horizontal_aperture": 20.955}
CAMERA_LENS: dict[str, dict] = {}  # per-camera overrides; missing names use the default


def camera_lens(name: str) -> dict:
    """Lens parameters for a camera, falling back to :data:`CAMERA_LENS_DEFAULT`."""
    return {**CAMERA_LENS_DEFAULT, **CAMERA_LENS.get(name, {})}


# The episode camera: a single wide view that holds the countertop AND the machine for the whole
# episode, so the counter's state is visible while the robot works. Merged into the rig only by
# the multi-object runner — adding it to CAMERAS would put a fourth render tile in every other
# script's rig (capacity_fill at 1080p, goal_configs' sheets, parity_check, check_scene) for no
# benefit there.
#
# Aimed at the centre of the measured must-see box, from the robot's front-left and above so the
# counter surface and the rack interior are both oblique rather than edge-on. Eye distance and
# lens are chosen together from the arithmetic above; VERIFY by rendering, not by trusting it.
EPISODE_CAMERA = {
    # Eye solved by projecting the must-frame box's CORNERS through the lens and binary-searching
    # the closest distance that still contains them with 5% margin — not from a bounding sphere,
    # which is orientation-agnostic and lands ~15% further out for no benefit.
    #
    # The box is the robot's working volume, the whole spawn rectangle, the machine, its open
    # door and the extended racks. It is bound by the HORIZONTAL footprint (~1.26 x 1.12 m), not
    # by the arm's height — capping the arm envelope anywhere from 0.75 to 1.05 m does not move
    # the answer.
    #
    # Worth knowing before retuning: once a fixed scene fills the frame, object pixel size is
    # set by the scene-to-object ratio, not the lens. A 63 mm cup is ~24 px at 1280 wide at ANY
    # focal length here (15/20/24 mm all give 23-25 px); a longer lens only pushes the eye
    # further back. Enough to read counter state, not to inspect a grasp — use the `front`
    # camera, or re-render offline with render_videos.py, for that.
    "eye": (-1.25, -1.65, 1.46),
    "target": (0.42, -0.06, 0.42),
    "lens": {"focal_length": 15.0, "horizontal_aperture": 20.955},
}

# ---------------------------------------------------------------------------------------------
# collision world
# ---------------------------------------------------------------------------------------------
CACHE_DIR = os.path.join(ASSETS_DIR, "cache")
COLLISION_MARGIN_M = 0.005  # hull inflation: the conservative-bias knob for FCL-vs-Isaac parity
# CoACD parameters per body (fallback key "default"); threshold is the concavity tolerance —
# lower = finer decomposition. The RACKS no longer go through CoACD: their meshes are generated
# by rack_gen from RACK_GEN below, and scripts/setup/decompose_meshes.py writes the generator's exact convex parts as
# the FCL pieces (zero decomposition slop on 3 mm wires). CoACD remains for the concave bodies
# whose geometry we don't control.
COACD = {
    "default": {"threshold": 0.05, "max_convex_hull": 32},
    "object": {"threshold": 0.03, "max_convex_hull": 32},  # keep the mug cavity open
}
CONTACT_FORCE_THRESH_N = 0.1  # Isaac ground-truth contact threshold for the parity check
# The robot base sits ON the pedestal by construction (permanent touching contact) and is
# bolted to the world — it can never produce a *new* collision. Excluded from both the Isaac
# ground truth and the FCL world checks, keeping the two sides mirror images.
PARITY_BODY_EXCLUDE = ["base_link"]
WORLD_CHECK_EXCLUDE = ["base_link"]

# ---------------------------------------------------------------------------------------------
# rack geometry generator (rack_gen) — single source of truth for BOTH replaced rack meshes.
# Design space = world-metric rack body frame: x = width, y = depth (y=0 the front edge, the
# end that extends toward the robot), z up from 0 at the lowest wire surface; meters.
# usd_prep authors these meshes into the derived v0 USD (replacing the ArtVIP flat baskets);
# scripts/setup/decompose_meshes.py writes the generator's convex parts as the FCL pieces. Vertical layout is derived:
# channel runners bottom at z=0, main runners raised by channel.drop, crossbars tangent on top
# (floor_top = crossbar top = the slot datum the Phase-E percentile must land on — everything
# floor-level therefore stays inside placement.py's 15 mm bottom-slab band).
# ---------------------------------------------------------------------------------------------
RACK_GEN_VERSION = 3  # v2: reference-appliance realism (Whirlpool WDTA50SAKZ / Bosch 800 /
#                       Frigidaire FDPC4314AS) — 3-gauge wires, 30 mm Whirlpool tine rows with
#                       candy-cane ends, fillets/ties/beads, fold-down insert row, wheels,
#                       front loading dip + handle, cup shelves, RackMatic blocks
#                       v3: cutlery basket in the lower rack's open zone (multi-object v1) —
#                       3-compartment plastic basket riding the rack, own mesh + material
RACK_GEN = {
    "E_shelf_1_04": {  # lower rack: rear plate bank + open zone (robot side) + bowl/slope side
        "usd_scale_x": 0.9191,  # authored x-scale on the body Xform (asserted at authoring)
        "footprint": (0.3663, 0.2868),  # world-space extents; == original basket footprint
        # 3-gauge hierarchy (real racks: frame >> runners > tines; real tine dia/pitch ~ 0.07)
        "wire_dia_heavy": 0.005,  # perimeter rails + the 2 outermost runners
        "wire_dia_load": 0.0036,  # depth-axis load runners
        "wire_dia_light": 0.0022,  # crossbars, tines, ribs, balusters, ties
        "wire_sides": 12,  # 12-gon: vertices exactly on -x/-y/-z -> exact assembled bounds
        # perimeter & rear guard: rear rim +29 % over the SIDE rails; the front rail dips for
        # loading clearance (Whirlpool/Bosch signature) with a center grab handle above it
        "rim_side_h": 0.045,
        "rim_front_h": 0.034,  # dipped front-rail height over front_dip_x
        # the loading dip spans the whole open zone (real racks run the low front rail across
        # the loading width) — it is also the mug's entry corridor under the raised upper rack
        "front_dip_x": (0.125, 0.340),
        "handle": {"x": (0.160, 0.210), "grip_z": 0.055},
        "rim_rear_h": 0.058,
        "rear_zone_y0": 0.190,  # where the raised rear-third side rails begin
        "corner_r": 0.016,
        "corner_segments": 4,
        "baluster_pitch": 0.035,
        "guard_mid_rail": True,  # retention mid rail halfway up the raised rear section
        # floor & zoned grid: open runner surface gaps 40 mm (real racks never exceed ~40);
        # one light dense runner per span midpoint under the bank -> 19 mm dense gaps
        "runner_xs": (0.029, 0.0725, 0.1160, 0.1595, 0.2065, 0.2501, 0.2937, 0.3373),
        "channel": {"x": (0.169, 0.197), "runner_xs": (0.176, 0.190), "drop": 0.004},
        "crossbar_ys": (0.025, 0.070, 0.115, 0.160),
        "slope_zones": ((0.004, 0.048),),  # drinkware ramp along the x=0 side wall
        "slope_deg": 6.0,
        "slope_sign": -1.0,  # floor descends toward the wall (mug leans into the wall)
        # rear plate bank: 12 tines/row at 30 mm pitch (11 slots — the Whirlpool W10728160
        # row pattern), rows 52 mm apart (true two-point plate support), +7 deg lean into the
        # guard; row ends are candy-cane hooks; straight tines get capped bead tips
        "plate_zone_y": (0.205, 0.285),
        "plate_rows_y": (0.220, 0.272),  # 0.212 would block the y=0.1434 slot columns (-6 mm)
        "plate_tine_pitch": 0.030,
        "plate_tine_xspan": (0.022, 0.352),
        "plate_tine_h": 0.070,
        "plate_tine_lean_deg": 7.0,
        "candy_cane": {"r": 0.012, "sweep_deg": 120.0, "segments": 4},
        "tine_fillet": {"r": 0.006, "segments": 3},  # U-bend fillet at every tine base
        "tine_tie_frac": 0.6,  # mid-height tie wire per row at 0.6 * tine height
        "tine_bead": {"dia_factor": 1.6, "len": 0.004},  # push-on tip caps (Frigidaire kit)
        # fold-down insert row (Bosch "flip tine, dark gray" / Whirlpool gray tine row): the
        # REAR row is a visually distinct second mesh — thicker spine, hinge bosses, stop clip
        "insert": {
            "row": 1,
            "spine_dia": 0.0055,
            "boss_dia": 0.009,
            "boss_len": 0.010,
            "clip_size": (0.012, 0.008, 0.008),
        },
        "bank_bar_ys": (0.197, 0.242, 0.280),
        # corrugated cradle ribs: V-profile under both tine rows, wavelength = tine pitch
        "rib_amplitude": 0.0025,
        # bowl tines: 42 mm high, 45 mm pitch, on the slope side
        "bowl_tine_xs": (0.055, 0.100),
        "bowl_tine_ys": (0.025, 0.070, 0.115, 0.160),
        "bowl_tine_h": 0.042,
        # roller wheels: 4, outer face exactly on the footprint plane, bottoms exactly z=0
        "wheels": {"dia": 0.022, "width": 0.008, "y_inset": 0.030},
        # open zone (flat floor, mug slots; drives the Phase-D probes + the Phase-E guarantee).
        # v3: the cutlery basket occupies the x-high end, killing the x=0.2432 slot columns —
        # the guarantee drops to the x=0.1832 columns x y={0.0834, 0.1434} (min_feasible_slots
        # 3 -> 2 in the scenario tables, encoded honestly)
        "open_zones": ((0.115, 0.360, 0.010, 0.190),),
        # cutlery basket (v3): 3-compartment plastic basket against the x-high open-zone end;
        # dividers split y into 3 bays; arch carry handle over the x-center line
        "basket": {
            "x": (0.264, 0.352),
            "y": (0.012, 0.180),
            "h": 0.095,
            "wall_t": 0.004,
            "floor_t": 0.003,
            "dividers_y": (0.068, 0.124),
            "handle": {"clearance": 0.022, "bar_dia": 0.008, "post_dia": 0.006},
        },
        "mass_kg": 0.9,  # authored explicitly (deterministic vs auto-mass); horizontal joint
        "sdf_resolution": 768,  # 0.48 mm voxel -> ~4.6 across a 2.2 mm wire
    },
    "E_shelf_03": {  # upper rack: glass/mug variant — shelves, divider, no plate bank
        "usd_scale_x": 0.94,
        "footprint": (0.3747, 0.2868),
        "wire_dia_heavy": 0.005,
        "wire_dia_load": 0.0036,
        "wire_dia_light": 0.0022,
        "wire_sides": 12,
        "rim_side_h": 0.040,  # level front (no loading dip on the upper rack)
        "rim_front_h": 0.040,
        # front pull/push handle (real upper racks have one; the rack_action engages it)
        "handle": {"x": (0.160, 0.210), "grip_z": 0.060},
        "rim_rear_h": 0.050,  # +25 %
        "rear_zone_y0": 0.190,
        "corner_r": 0.016,
        "corner_segments": 4,
        "baluster_pitch": 0.035,
        "guard_mid_rail": True,
        "runner_xs": (0.030, 0.0736, 0.1172, 0.1608, 0.2044, 0.2480, 0.2916, 0.3352),  # 40 mm
        "crossbar_ys": (0.025, 0.070, 0.115, 0.160, 0.205, 0.250),  # 42 mm gaps
        "slope_zones": ((0.004, 0.048), (0.3267, 0.3707)),  # ramps along BOTH side walls
        "slope_deg": 6.0,
        "slope_sign": 1.0,  # ascends toward the wall (keeps wire bottoms above z=0)
        "divider_tine_x": 0.187,
        "divider_tine_ys": (0.025, 0.070, 0.115, 0.160, 0.205, 0.250),
        "divider_tine_h": 0.040,
        # fold-down cup shelves with stemware scallops, confined over the slope zones so the
        # mug strips stay clear (Bosch two cup shelves / Whirlpool push-up shelf)
        "cup_shelf": {
            "depth": 0.055,
            "y_span": (0.045, 0.135),
            "mount_z": 0.030,
            "tilt_deg": 13.0,
            "rungs": 5,
            "scallops": 3,
            "scallop_r": 0.008,
        },
        # Bosch RackMatic lever end caps on the outer side-rail faces (size = x, y, z extents)
        "rackmatic_blocks": {"size": (0.014, 0.026, 0.012), "ys": (0.060, 0.220), "z": 0.030},
        "wheels": {"dia": 0.022, "width": 0.008, "y_inset": 0.030},
        "open_zones": ((0.068, 0.182, 0.020, 0.180), (0.193, 0.307, 0.020, 0.180)),
        "mass_kg": 0.7,
        "sdf_resolution": 768,
    },
}

# ---------------------------------------------------------------------------------------------
# placement goals
# ---------------------------------------------------------------------------------------------
SLOT_TOL_LATERAL_M = 0.015
SLOT_TOL_TILT_DEG = 10.0
GOAL_POSE_SAMPLES_PER_SLOT = 64
SETTLE_STEPS = 300  # success criterion: pose holds for this many physics steps after release
# Slot derivation (the ArtVIP lower rack is a shallow WIRE BASKET, not a plate-tine rack — the
# mug STANDS on the wire floor; a "slot" is a standing position on a grid). Slot centers form
# an overlapping candidate grid (one object placed per trial), spanning the basket from the
# protruding front to the deep interior — rear-slot infeasibility is expected signal.
SLOT_RIM_INSET_M = 0.055  # keep the mug footprint away from the basket rim walls
SLOT_GRID_PITCH_M = 0.06  # candidate-center spacing (overlap allowed)
RELEASE_HOVER_M = 0.012  # goal poses hover the object above the wire floor (> collision margin,
#                          small enough that the release drop is a non-event)

# Per-placement-mode geometry and success tolerances. These used to be literals scattered
# through placement.py (bowl slot positions, the plate seating bar, the basket drop offset, the
# basket's hover override, and every non-floor_stand success tolerance), which made "where does
# a goal come from" unanswerable without reading the derivation code. They are values MEASURED
# against the rack geometry — see docs/success_criteria.md — and relocating them here changed
# none of them, so existing caches and the frozen mug baseline stay bit-identical.
#
# Keys per mode:
#   release_hover_m  goal poses hover the object this far above the seating datum
#   tol_*            success tolerances (docs/success_criteria.md); floor_stand aliases the
#                    SLOT_TOL_* constants above so the v0 criteria have a single source
PLACEMENT_MODES: dict[str, dict] = {
    "floor_stand": {
        "release_hover_m": RELEASE_HOVER_M,
        "tol_lateral_m": SLOT_TOL_LATERAL_M,
        "tol_tilt_deg": SLOT_TOL_TILT_DEG,
        "tol_bottom_m": 0.02,
    },
    "plate_slot": {
        # dinner plates seat forward, bottom edge on the y 0.197 bank bar (rack frame); the
        # disc spans the full diameter, so smaller discs may seat deeper via spec params
        "seat_y_m": 0.197,
        "release_hover_m": RELEASE_HOVER_M,
        "default_lean_deg": 7.0,  # fallback when the slot carries no measured tine lean
        "tol_lateral_m": 0.012,  # off-gap drift along the tine pitch direction
        "tol_tilt_deg": 12.0,  # face-normal deviation, flip-insensitive
        "tol_bottom_m": 0.02,
    },
    "bowl_lean": {
        # lean positions over the drinkware slope, against the bowl tines
        "slot_x_m": 0.070,
        "slot_ys_m": (0.060, 0.105, 0.150),
        "slot_width_m": 0.110,
        "default_lean_deg": 48.0,  # opening down-slope
        "release_hover_m": RELEASE_HOVER_M,
        "tol_lateral_m": 0.04,
        "tol_tilt_deg": 20.0,
        "tol_bottom_m": 0.06,
    },
    "basket_drop": {
        # the arch carry-handle bar runs along y directly over every bay center, so a centered
        # descent always hits it — the drop point is offset in x
        "drop_x_offset_m": -0.020,
        # gravity does the insertion: release from a genuine hover, not the 12 mm used elsewhere
        "release_hover_m": 0.060,
        "tol_lateral_pad_m": 0.005,  # slack added to the bay half-width in y
        "tol_bottom_min_m": -0.005,  # settled center may not sink below the bay floor
        "default_top_z_m": 0.092,
    },
}


def placement_mode_params(mode: str) -> dict:
    """Geometry and tolerances for a placement mode.

    Args:
        mode: Placement-mode name (a key of :data:`PLACEMENT_MODES`).

    Returns:
        The mode's parameter dict.
    """
    if mode not in PLACEMENT_MODES:
        raise ValueError(f"no placement-mode parameters for {mode!r} (have {sorted(PLACEMENT_MODES)})")
    return PLACEMENT_MODES[mode]

# ---------------------------------------------------------------------------------------------
# rack manipulation + countertop pick (the both_in / both_out trial choreography)
# ---------------------------------------------------------------------------------------------
# Countertop: the ArtVIP tub is open-topped in collision; freestanding dishwashers have a
# worktop. usd_prep authors this slab onto E_body_5 in the derived USDs — it is also the
# objects' initial resting surface. Shell top measured at world z 0.47.
#
# Sized from a MEASURED reachability map, not chosen (scripts/setup/reach_map.py, which grids
# the countertop plane and runs the runner's own pick-feasibility idiom — IK at the pre-grasp
# hover AND at the grasp pose, both collision-filtered — per demo class). Two facts came out of
# that map and fix the geometry:
#   - Nothing beyond world x ~0.80 is reachable for any class, so the slab's far half is
#     decorative. It is kept (a worktop that stops at the machine's mid-depth looks wrong and
#     costs nothing) but never spawned on — see TASK["spawn_rect_w"].
#   - The counter must NOT grow toward the robot past x 0.65: the door opens to a tip at
#     x 0.271 and the robot loads the racks through that space, so an overhang there would
#     block the task it exists to serve.
# Growth therefore goes sideways along the counter run: y [-0.240, 0.242] -> [-0.600, 0.440].
# Surface 0.190 -> 0.411 m^2, against 0.20 m^2 for the entire 15-class library laid flat.
COUNTERTOP_SIZE = (0.395, 1.040, 0.020)  # world-aligned box extents [m]
COUNTERTOP_CENTER_W = (0.8475, -0.080, 0.48)  # world center; top surface at z 0.49
# Object staging poses: upright on the countertop at the robot-nearest corner (the wrist
# IK target lands at ~0.81 of the 0.85 m reach — verified with the analytic IK offline). Yaw
# orients the handle so the fixed calibrated grasp transform stays IK-reachable. This is the
# ACTIVE-OBJECT view (rewritten by set_active_object); tuple of ((x, y, z), yaw_deg) staging
# poses, one per trial instance. Entry 0 reproduces the frozen v0 mug pose.
OBJECT_COUNTERTOP_POSES_W: tuple = (
    ((0.665, -0.185, 0.5307), 0.0),  # root (= bbox center); mug base at z 0.49
    ((0.665, -0.105, 0.5307), 0.0),  # second staging spot, one footprint toward +y
)
PICK_HOVER_M = 0.10  # planned pre-grasp TCP hover above the grasp pose; the descent is a
#                      scripted straight line gated by the calibrated pinch band, not FCL
#                      (the goal pose is inside the inflated-hull margin of the mug by design)
PICK_DESCEND_STEPS = 120
PICK_LIFT_M = 0.12  # straight lift after weld-on, before planning to the slot
# Rack slide: drive-synchronized manipulation — the gripper visibly engages the rack's front
# handle while the rack joint's drive target ramps to rack_action["to"] and the TCP tracks the
# moving handle (same visible-contact + guaranteed-actuation methodology as the mug weld).
RACK_SLIDE_STEPS = 240  # 4 s at SIM_DT for the 0.2 m travel
RACK_HANDLE_APERTURE_RAD = 0.70  # near-closed pinch around the 3.6 mm handle rod (pull)
RACK_PUSH_APERTURE_RAD = 0.78  # closed-fist contact for push
RACK_SLIDE_TOL_M = 0.005  # the rack must settle within this of the action target
RACK_TRACK_TOL_M = 0.020  # max TCP-vs-handle tracking error during the slide
RACK_APPROACH_HOVER_M = 0.08  # planned pre-engage TCP offset above/behind the handle

# ---------------------------------------------------------------------------------------------
# planning + execution
# ---------------------------------------------------------------------------------------------
# Placement always happens in the reconfigured machine state (lower rack out, upper in — the
# rack_action runs first), so the planning problem matches the validated open-approach layout;
# the rack-approach and pick plans carry nothing and are easy. 20 s is generous headroom.
PLAN_TIME_BUDGET_S = 20.0
PLAN_RRT_RANGE_RAD = 0.5  # smaller extension steps handle the cluttered machine front reliably
GOALS_PER_PLAN = 64  # random goal-set subset handed to OMPL per trial
# planning bounds: full joint limits minus a small margin (config-tunable; tighten if RRT
# wanders into pointless windups)
PLAN_JOINT_BOUNDS_MARGIN_RAD = 0.05
PLAN_VALIDITY_RESOLUTION_RAD = 0.015
EXEC_JOINT_SPEED_RAD_S = 0.5  # constant joint-speed cap for time parameterization

# Which planner the experiment runner uses by default, and per-algorithm parameters. Names are
# registry keys (see dishsim.planners.registry.available()); the runner's --planner and
# repeatable --planner_param k=v override these. Adding an algorithm never touches the runner.
PLANNER = "rrt_connect"
PLANNER_PARAMS: dict[str, dict] = {
    # bidirectional, returns on first connection — the validated default
    "rrt_connect": {"range_rad": PLAN_RRT_RANGE_RAD},
    # optimizing: always consumes its full budget, so it gets a smaller one than the default
    "rrt_star": {"range_rad": PLAN_RRT_RANGE_RAD, "budget_s": 10.0},
    # optimizing, batch-sampled; algorithmically distinct from the RRT family
    "bit_star": {"budget_s": 10.0},
    # roadmap rebuilt per query; single-goal only in this OMPL build (see planners/prm.py)
    "prm": {"budget_s": 10.0},
}

# ---------------------------------------------------------------------------------------------
# multi-object task (the dishsim.task layer)
# ---------------------------------------------------------------------------------------------
# Everything the task sequencer is allowed to decide from. The sequencer chooses WHICH object to
# pick next; it never invents geometry — spawn bounds, goal slot pools and every tolerance come
# from here. The motion layer below it never reads this block at all.
TASK: dict = {
    # Episode composition. A multi-object PICK task may only draw from classes the robot can
    # actually pick off the countertop, which is a stricter bar than robot_demo:
    #
    #   grasp family   classes                 real countertop pick?
    #   rim_diam       mug, cup, tumbler       yes — approach, close, weld, lift
    #   edge_pinch     plate                   no  — START_WELDED in run_trials.py:135
    #   rim_edge       bowl                    no  — START_WELDED
    #   handle_pinch   fork                    no  — START_WELDED
    #
    # The three START_WELDED families are teleported into the gripper at the carry pose so
    # their PLACEMENT can be exercised; their pick has never been calibrated or demonstrated.
    # Including them here would make an episode that reports "picked" for objects it teleported,
    # so the default pool is the three families that survive a genuine pick. Widening it is a
    # grasp-calibration job (setup/calibrate_grasp.py per class), not a task-layer one.
    "classes": ("mug", "cup", "tumbler"),
    # Which classes cannot be picked is NOT listed here: it is derived from the grasp FAMILY via
    # WELD_ACQUIRE_FAMILIES, so a class calibrated later stops being weld-acquired automatically
    # instead of leaving a hand-maintained list to drift out of date.
    # Bounded by DESTINATION capacity, not by countertop room — the counter comfortably holds
    # far more than the machine can accept from the robot. Two measured limits stack:
    #
    #   reachability  only 4 of the 15 lower-rack grid slots have any goal configurations
    #                 (ids 1, 2, 6, 7); the rest sit where the carried object cannot be brought
    #                 in. Empty goal sets there are expected signal, not a bug.
    #   overlap       those 4 form a 2x2 block at the 60 mm SLOT_GRID_PITCH_M. The grid is an
    #                 *overlapping candidate* grid built for one-object-per-trial coverage, so
    #                 only the ~85 mm diagonals are simultaneously occupiable.
    #
    # Net simultaneous capacity is therefore 2. Raising this without widening the slot pool
    # just produces items the assigner honestly reports it cannot place.
    "n_objects": 2,
    # EXPLICIT composition: object type -> exact count, or an inclusive (lo, hi) range whose
    # value is drawn per episode from the layout seed. Set this and it fully determines what
    # spawns, replacing the uniform draw over "classes"/"n_objects" above (which stays as the
    # fallback when this is None, so existing runs are unaffected).
    #
    #     "spawn_counts": {"cup": (2, 4), "tumbler": 1},
    #
    # The expanded list is SHUFFLED with the same seeded generator before layout. Placement
    # order is draw order, so an unshuffled list would always let the first-listed type claim
    # the best countertop space — composition should be yours to fix, position should not be.
    "spawn_counts": None,
    # Clear gap required between two occupied slot centres, on top of both objects' body radii.
    "slot_separation_margin_m": 0.010,
    # Countertop spawn bounds [m, world]. MEASURED by scripts/setup/reach_map.py as the largest
    # rectangle on the worktop where at least one demo class is pickable; per-class acceptance
    # inside it ranges 50% (plate, whose edge_pinch has a mid-y hole) to 89% (bowl), which is
    # why every item is reach-checked individually and rejects are resampled rather than
    # trusting the rectangle wholesale.
    "spawn_rect_w": {"x_min": 0.680, "x_max": 0.800, "y_min": -0.580, "y_max": 0.420},
    "min_separation_m": 0.015,  # clear gap between object footprint circles at spawn
    "spawn_hover_m": 0.004,  # objects spawn just above the surface and settle onto it
    "settle_steps": 120,  # physics steps after spawning, before the episode begins
    "max_spawn_resamples": 400,  # per-item rejection budget inside one layout attempt
    "max_layout_retries": 10,  # whole-layout resamples (Stage B: settling can break reach)
    # Stage B stacking. Uniform sampling almost never lands one footprint on another, so with
    # --allow_stacking this fraction of objects is aimed at an already-placed one instead; the
    # jitter (as a fraction of the base object's radius) keeps the stack imperfect, which is
    # what makes settling non-trivial.
    "stack_fraction": 0.5,
    "stack_jitter_frac": 0.25,
    # Goal slots inside the machine, per placement mode. None = every derived slot, in
    # derivation order; a tuple restricts and orders the pool (front-to-back, say). The
    # sequencer allocates an unused slot from the pool for each item.
    "slot_pools": {
        "floor_stand": None,
        "plate_slot": None,
        "bowl_lean": None,
        "basket_drop": None,
    },
    # Goal slots per object TYPE, as an ORDERED list of slot NAMES (see
    # dishsim.placement.slot_names, which derives them from the rack geometry rather than
    # hardcoding ids — ids are positional and silently re-point if SLOT_GRID_PITCH_M changes).
    # Objects of a type consume the list in order; a slot already taken, overlapping an assigned
    # one, or with no reachable goal configurations for that class is SKIPPED rather than
    # failing, and an object whose list runs out is reported unplaced. Falls back to
    # slot_pools[mode], then to every derived slot, when a type has no entry here.
    #
    #     "type_slots": {"plate": ("gap_04", "gap_05"), "mug": ("mid_centre",)},
    "type_slots": None,
    # Machine rack state. Either a named state (a key of SCENARIOS / INTERNAL_STATES) or
    # explicit per-rack extensions in metres, which resolve to the matching named state:
    #
    #     "rack_state": "placement"
    #     "rack_state": {"lower_m": -0.20, "upper_m": 0.0}
    #
    # The two racks are independently articulated (limits [-0.20, 0.00] m each; 0 = stowed).
    # Extensions are part of geometry.config_hash(), and caches are keyed by state NAME, so an
    # unbaked combination cannot be run — resolve_rack_state() fails with the commands to bake
    # it rather than planning against a stale world.
    "rack_state": "placement",
    # Which camera the episode MP4 is written from (see config.CAMERAS + EPISODE_CAMERA).
    "video_camera": "episode",
    "cost_fn": "nearest_first",  # pick-order heuristic; see dishsim.task.cost.available()
    # Stage B — support graph
    "support_backend": "both",  # "contact" | "geometric" | "both" (both cross-checks and logs)
    "support_gap_m": 0.008,  # max vertical gap still counted as resting-on
    "support_overlap_frac": 0.10,  # min footprint-circle overlap counted as resting-on
    "support_force_thresh_n": 0.05,  # object-object contact above this counts as touching  # min footprint-circle overlap counted as resting-on
    # Stage C — blocked grasps and recovery
    "grasp_yaw_samples": 12,  # candidate grasp yaws probed against the CURRENT world
    "grasp_yaw_samples_wide": 36,  # recovery step 1 widens the sweep to this
    "max_recovery_attempts": 2,
    "recovery_settle_steps": 90,  # recovery step 2 lets a leaning pile relax
    "pose_stale_tol_m": 0.010,  # beyond this the cached grasp is stale -> recompute + replan
    "pose_stale_tol_deg": 10.0,
    # Home anchoring — every episode starts and ends at HOME_Q. This is the per-joint deviation
    # treated as "already home"; below it the retreat is skipped rather than replanned. It is
    # NOT a placement tolerance: it only decides whether the arm has to move.
    "home_tol_rad": 0.05,
}

# =============================================================================================
# object library (multi-object v1)
# =============================================================================================
# Each ObjectSpec is the single source of truth for one manipulable object class. The
# module-level OBJECT_* / GRASP_* / GRIP_* constants above are the ACTIVE-OBJECT VIEW:
# set_active_object() rewrites them in place before scene imports — the same pattern as
# apply_scenario(), so every existing consumer keeps reading plain module attributes. The
# "mug" entry reproduces the frozen v0 constants exactly (and keeps cache_name "025_mug" so
# the baseline cache hash is byte-stable).
#
# Scale factors: the ArtVIP dishwasher is compact (lower rack 0.366 x 0.287 m, 154 mm
# inter-rack clearance, 30 mm tine pitch) — real-size dinner plates cannot fit, so every
# sourced object is scaled to rack-proportional size. `scale` documents that factor against
# the source asset; dims below are the TARGET scaled dims, re-measured and frozen by
# scripts/setup/build_object_assets.py (numeric-provenance rule).
#
# Masses are design choices for the scaled objects (ceramic/steel/plastic at that size), not
# volume-scaled YCB masses (which would be unrealistically light); the mug mass is measured.

from dataclasses import dataclass, field  # noqa: E402


@dataclass(frozen=True)
class GraspSpec:
    """How the gripper pinches this object class.

    Families (carry orientation + contact patch):
      - ``rim_diam``: upright carry, pads on the outer wall across the DIAMETER (mug family).
      - ``rim_edge``: upright carry, pads straddle the rim WALL (bowl, container).
      - ``edge_pinch``: on-edge (vertical) carry for flat discs, pads across the face
        thickness at the rim (plate, saucer, lid).
      - ``handle_pinch``: flat pick, pads across the handle width (cutlery, utensils).
      - ``stem_pinch``: registry-only (wine glass); never robot-executed.
    """

    family: str
    grasp_width_m: float  # object width between the pads at the contact patch [m]
    rim_tcp_z_m: float = -0.020  # engagement offset of the grasped feature along tool z [m]
    grasp_point_m: float = 0.0  # handle_pinch only: grasp-point offset along the long axis [m]
    aperture_rad: float | None = None  # calibrated by scripts/setup/calibrate_grasp.py; None until frozen
    force_min_n: float | None = None  # calibrated steady per-pad band [N]
    force_max_n: float | None = None
    force_exec_max_n: float | None = None  # dynamic per-pad allowance during motion [N]
    target_force_n: float = 5.0  # scripts/setup/calibrate_grasp.py staircase target [N]


@dataclass(frozen=True)
class PlacementSpec:
    """Default placement mode for demos/fill.

    Modes: ``floor_stand`` | ``plate_slot`` | ``bowl_lean`` | ``basket_drop`` (robot-capable)
    and ``upside_down`` | ``stem_scallop`` | ``flat_lay`` (capacity-fill only).
    """

    mode: str
    rack: str  # "lower" | "upper" | "basket"
    params: dict = field(default_factory=dict)


@dataclass(frozen=True)
class ObjectSpec:
    """One manipulable object class (dims in the object's own canonical frame).

    Frame convention: NEW assets are authored Z-up with the origin at the bbox center
    (``axis_obj = (0, 0, 1)``); the legacy mug keeps its validated Y-up frame. ``bbox_half``
    is origin-to-face half extents [m]; ``body_center_uv`` is the axis-perpendicular offset
    (u, v) of the body circle center from the origin [m] (for the Y-up mug: (x, z)).
    """

    name: str
    source: str  # "isaac_ycb" | "ycb16k" | "procedural"
    source_id: str | None  # YCB id / prop_gen builder name
    scale: float  # documented scale factor vs the source asset
    mass_kg: float
    bbox_half: tuple[float, float, float]
    axis_obj: tuple[float, float, float]  # object "up" (bottom -> opening) direction
    body_center_uv: tuple[float, float]
    rim_radius_m: float
    height_m: float  # extent along axis_obj [m]
    grasp: GraspSpec
    placement: PlacementSpec
    coacd: dict  # scripts/setup/decompose_meshes.py params, or {"analytic": True} for prop_gen part lists
    countertop_poses_w: tuple = ()  # ((x, y, z), yaw_deg) staging poses; demo classes only
    robot_demo: bool = False
    cache_name: str | None = None  # manifest/hash name; defaults to `name`
    usd_basename: str | None = None  # defaults to f"{name}_physics.usd"

    @property
    def object_name(self) -> str:
        return self.cache_name or self.name

    @property
    def usd_path(self) -> str:
        return os.path.join(ASSETS_DIR, "props", self.usd_basename or f"{self.name}_physics.usd")


OBJECTS: dict[str, ObjectSpec] = {
    # ---- the frozen v0 mug (measured 2026-07-29/31; do not edit) ------------------------------
    "mug": ObjectSpec(
        name="mug",
        source="isaac_ycb",
        source_id="025_mug",
        scale=1.0,
        mass_kg=0.118,
        bbox_half=(0.0585, 0.0407, 0.0465),
        axis_obj=(0.0, 1.0, 0.0),  # legacy Axis_Aligned asset lies on its side
        body_center_uv=(-0.0110, 0.0),
        rim_radius_m=0.0399,
        height_m=0.0813,
        grasp=GraspSpec(
            family="rim_diam",
            grasp_width_m=0.0798,  # 2 * rim radius
            rim_tcp_z_m=-0.0200,
            aperture_rad=0.058,
            force_min_n=1.7,
            force_max_n=15.4,
            force_exec_max_n=12.0,
        ),
        placement=PlacementSpec(mode="floor_stand", rack="lower"),
        coacd={"threshold": 0.03, "max_convex_hull": 32},
        countertop_poses_w=(((0.665, -0.185, 0.5307), 0.0), ((0.665, -0.105, 0.5307), 0.0)),
        robot_demo=True,
        cache_name="025_mug",
        usd_basename="025_mug_physics.usd",
    ),
    # ---- YCB google_16k dishware (scaled to fit; dims frozen from scripts/setup/build_object_assets.py measurement) -----
    "plate": ObjectSpec(
        name="plate",
        source="ycb16k",
        source_id="029_plate",
        scale=0.54,  # real dia 258 mm -> 139 mm (top clears the stowed upper rack's runners
        #              by ~4 mm; 0.55 grazed them by 1 mm in the closability z-budget check)
        mass_kg=0.20,
        bbox_half=(0.0702, 0.0705, 0.0072),
        axis_obj=(0.0, 0.0, 1.0),
        body_center_uv=(0.0, 0.0),
        rim_radius_m=0.0706,
        height_m=0.0144,
        grasp=GraspSpec(
            family="edge_pinch", grasp_width_m=0.006, rim_tcp_z_m=-0.014,
            # first-contact aperture from the 2026-08-07 staircase (right pad touches at
            # theta_meas 0.647): the visible close stops at the rim; the weld carries
            # (pinch-band calibration is not applicable to a rigid-weld thin disc —
            # the contact is one-sided and binary).
            aperture_rad=0.640,
        ),
        placement=PlacementSpec(mode="plate_slot", rack="lower", params={"lean_deg": 7.0}),
        coacd={"threshold": 0.02, "max_convex_hull": 48},
        countertop_poses_w=(((0.70, -0.185, 0.562), 0.0), ((0.70, -0.10, 0.562), 0.0)),
        robot_demo=True,
    ),
    "saucer": ObjectSpec(
        name="saucer",
        source="ycb16k",
        source_id="029_plate",
        scale=0.42,  # real dia 258 mm -> 108 mm side plate
        mass_kg=0.12,
        bbox_half=(0.0546, 0.0548, 0.0056),
        axis_obj=(0.0, 0.0, 1.0),
        body_center_uv=(0.0, 0.0),
        rim_radius_m=0.0549,
        height_m=0.0112,
        grasp=GraspSpec(family="edge_pinch", grasp_width_m=0.005, rim_tcp_z_m=-0.012),
        placement=PlacementSpec(mode="plate_slot", rack="lower", params={"lean_deg": 7.0}),
        coacd={"threshold": 0.02, "max_convex_hull": 48},
    ),
    "bowl": ObjectSpec(
        name="bowl",
        source="ycb16k",
        source_id="024_bowl",
        scale=0.68,  # real dia 159 mm -> 108 mm cereal bowl
        mass_kg=0.15,
        bbox_half=(0.0549, 0.0548, 0.0187),
        axis_obj=(0.0, 0.0, 1.0),
        body_center_uv=(0.0, 0.0),
        rim_radius_m=0.0551,
        height_m=0.0374,
        grasp=GraspSpec(
            family="rim_edge", grasp_width_m=0.004, rim_tcp_z_m=0.030,
            # first-contact aperture from the 2026-08-07 staircase (60 N spike within
            # one 0.002 rad plateau at theta 0.716): visible close stops just shy;
            # the weld carries.
            aperture_rad=0.700,
        ),
        # rim_z +0.030: at -0.016 the fingertips reached ~34 mm below the rim and crushed
        # the bowl interior at full open (measured 88 N in the scripts/setup/calibrate_grasp.py open gate)
        placement=PlacementSpec(mode="bowl_lean", rack="lower", params={"lean_deg": 48.0}),
        coacd={"threshold": 0.03, "max_convex_hull": 32},
        countertop_poses_w=(((0.665, -0.185, 0.5087), 0.0), ((0.665, -0.10, 0.5087), 0.0)),
        robot_demo=True,
    ),
    "cup": ObjectSpec(
        name="cup",
        source="ycb16k",
        source_id="065-a_cups",
        scale=1.10,  # stacking cup A ~ 55 mm dia -> 60 mm teacup
        mass_kg=0.06,
        bbox_half=(0.0314, 0.0316, 0.0338),
        axis_obj=(0.0, 0.0, 1.0),
        body_center_uv=(0.0, 0.0),
        rim_radius_m=0.0317,
        height_m=0.0677,
        grasp=GraspSpec(
            family="rim_diam", grasp_width_m=0.0634, rim_tcp_z_m=-0.004,
            # frozen from the 2026-08-07 scripts/setup/calibrate_grasp.py staircase at the minimal both-pads
            # point (pads [13.7, 2.5] N; the 3/5 N crossings are one-sided on this
            # small rim). Band = steady/3 .. 3x steady around the ~8.1 N mean.
            aperture_rad=0.264, force_min_n=2.0, force_max_n=24.3, force_exec_max_n=16.2,
        ),
        placement=PlacementSpec(mode="floor_stand", rack="lower"),
        coacd={"threshold": 0.03, "max_convex_hull": 32},
        countertop_poses_w=(((0.665, -0.185, 0.5238), 0.0), ((0.665, -0.105, 0.5238), 0.0)),
        robot_demo=True,
    ),
    # ---- YCB google_16k cutlery + utensils (scaled to the basket) -----------------------------
    "fork": ObjectSpec(
        name="fork",
        source="ycb16k",
        source_id="030_fork",
        scale=0.60,  # real 198 mm -> 119 mm (basket interior is 168 mm long, 95 mm tall)
        mass_kg=0.030,
        bbox_half=(0.0592, 0.0082, 0.0046),
        axis_obj=(1.0, 0.0, 0.0),  # long axis; head at +x, handle at -x
        body_center_uv=(0.0, 0.0),
        rim_radius_m=0.0082,
        height_m=0.1185,
        grasp=GraspSpec(
            family="handle_pinch", grasp_width_m=0.009, rim_tcp_z_m=0.005, grasp_point_m=-0.038,
            target_force_n=3.0, aperture_rad=0.74,  # free-pick close: 0.70 never touched the centered free fork
            # (0 N both pads); the welded-curve crossing 0.8 dragged it ~20 mm (22.9 N)
            force_min_n=0.5, force_max_n=40.0, force_exec_max_n=35.0,
            # exec cap raised after measurement: the welded one-sided handle contact
            # (~15 N static per the staircase) spikes to ~28 N under motion dynamics
        ),
        placement=PlacementSpec(mode="basket_drop", rack="basket"),
        coacd={"threshold": 0.05, "max_convex_hull": 16},
        countertop_poses_w=(((0.68, -0.19, 0.4946), 90.0), ((0.68, -0.11, 0.4946), 90.0)),
        robot_demo=True,
    ),
    "spoon": ObjectSpec(
        name="spoon",
        source="ycb16k",
        source_id="031_spoon",
        scale=0.60,  # real 195 mm -> 117 mm
        mass_kg=0.030,
        bbox_half=(0.0587, 0.0125, 0.0063),
        axis_obj=(1.0, 0.0, 0.0),
        body_center_uv=(0.0, 0.0),
        rim_radius_m=0.0125,
        height_m=0.1174,
        grasp=GraspSpec(
            family="handle_pinch", grasp_width_m=0.009, rim_tcp_z_m=-0.010, grasp_point_m=-0.038,
            target_force_n=3.0,
        ),
        placement=PlacementSpec(mode="basket_drop", rack="basket"),
        coacd={"threshold": 0.05, "max_convex_hull": 16},
    ),
    "knife": ObjectSpec(
        name="knife",
        source="ycb16k",
        source_id="032_knife",
        scale=0.60,  # real 215 mm -> 129 mm
        mass_kg=0.040,
        bbox_half=(0.0644, 0.0064, 0.0047),
        axis_obj=(1.0, 0.0, 0.0),
        body_center_uv=(0.0, 0.0),
        rim_radius_m=0.0064,
        height_m=0.1289,
        grasp=GraspSpec(
            family="handle_pinch", grasp_width_m=0.009, rim_tcp_z_m=-0.010, grasp_point_m=-0.042,
            target_force_n=3.0,
        ),
        placement=PlacementSpec(mode="basket_drop", rack="basket"),
        coacd={"threshold": 0.05, "max_convex_hull": 16},
    ),
    "spatula": ObjectSpec(
        name="spatula",
        source="ycb16k",
        source_id="033_spatula",
        scale=0.45,  # real ~350 mm -> 158 mm serving tool
        mass_kg=0.050,
        bbox_half=(0.0700, 0.0188, 0.0074),
        axis_obj=(1.0, 0.0, 0.0),
        body_center_uv=(0.0, 0.0),
        rim_radius_m=0.0188,
        height_m=0.1401,
        grasp=GraspSpec(
            family="handle_pinch", grasp_width_m=0.012, rim_tcp_z_m=-0.010, grasp_point_m=-0.050,
            target_force_n=3.0,
        ),
        placement=PlacementSpec(mode="flat_lay", rack="upper"),
        coacd={"threshold": 0.05, "max_convex_hull": 16},
    ),
    "pitcher": ObjectSpec(
        name="pitcher",
        source="ycb16k",
        source_id="019_pitcher_base",
        scale=0.50,  # real 242 mm tall -> 121 mm carafe (fits under the tub ceiling)
        mass_kg=0.15,
        bbox_half=(0.0373, 0.0362, 0.0606),
        axis_obj=(0.0, 0.0, 1.0),
        body_center_uv=(0.0, 0.0),
        rim_radius_m=0.0475,  # max radial incl. spout (fill-only spacing bound)
        height_m=0.1212,
        grasp=GraspSpec(family="rim_diam", grasp_width_m=0.0724, rim_tcp_z_m=-0.018),
        placement=PlacementSpec(mode="floor_stand", rack="lower"),
        coacd={"threshold": 0.03, "max_convex_hull": 32},
    ),
    # ---- procedural drinkware + containers (prop_gen; dims exact by construction) -------------
    "tumbler": ObjectSpec(
        name="tumbler",
        source="procedural",
        source_id="tumbler",
        scale=1.0,
        mass_kg=0.090,
        bbox_half=(0.0300, 0.0300, 0.0525),
        axis_obj=(0.0, 0.0, 1.0),
        body_center_uv=(0.0, 0.0),
        rim_radius_m=0.0300,
        height_m=0.1050,
        grasp=GraspSpec(family="rim_diam", grasp_width_m=0.0600, rim_tcp_z_m=-0.018, aperture_rad=0.303, force_min_n=1.6, force_max_n=14.7, force_exec_max_n=12.0,),
        placement=PlacementSpec(mode="floor_stand", rack="lower"),
        coacd={"analytic": True},
        countertop_poses_w=(((0.665, -0.185, 0.5425), 0.0), ((0.665, -0.105, 0.5425), 0.0)),
        robot_demo=True,
    ),
    "wine_glass": ObjectSpec(
        name="wine_glass",
        source="procedural",
        source_id="wine_glass",
        scale=1.0,
        mass_kg=0.100,
        bbox_half=(0.0290, 0.0290, 0.0600),
        axis_obj=(0.0, 0.0, 1.0),
        body_center_uv=(0.0, 0.0),
        rim_radius_m=0.0290,
        height_m=0.1200,
        grasp=GraspSpec(family="stem_pinch", grasp_width_m=0.008),  # never robot-executed
        placement=PlacementSpec(mode="stem_scallop", rack="upper"),
        coacd={"analytic": True},
    ),
    "serving_spoon": ObjectSpec(
        name="serving_spoon",
        source="procedural",
        source_id="serving_spoon",
        scale=1.0,
        mass_kg=0.060,
        bbox_half=(0.0900, 0.0200, 0.0060),
        axis_obj=(1.0, 0.0, 0.0),
        body_center_uv=(0.0, 0.0),
        rim_radius_m=0.0200,
        height_m=0.1800,
        grasp=GraspSpec(
            family="handle_pinch", grasp_width_m=0.012, rim_tcp_z_m=-0.010, grasp_point_m=-0.060,
            target_force_n=3.0,
        ),
        placement=PlacementSpec(mode="basket_drop", rack="basket"),
        coacd={"analytic": True},
    ),
    "container": ObjectSpec(
        name="container",
        source="procedural",
        source_id="container",
        scale=1.0,
        mass_kg=0.110,
        bbox_half=(0.0600, 0.0450, 0.0275),
        axis_obj=(0.0, 0.0, 1.0),
        body_center_uv=(0.0, 0.0),
        rim_radius_m=0.0450,  # half the short side (rim_edge grasps the long wall)
        height_m=0.0550,
        grasp=GraspSpec(family="rim_edge", grasp_width_m=0.0025, rim_tcp_z_m=-0.014),
        placement=PlacementSpec(mode="upside_down", rack="upper"),
        coacd={"analytic": True},
    ),
    "lid": ObjectSpec(
        name="lid",
        source="procedural",
        source_id="lid",
        scale=1.0,
        mass_kg=0.060,
        bbox_half=(0.0630, 0.0480, 0.0040),
        axis_obj=(0.0, 0.0, 1.0),
        body_center_uv=(0.0, 0.0),
        rim_radius_m=0.0480,
        height_m=0.0080,
        grasp=GraspSpec(family="edge_pinch", grasp_width_m=0.008, rim_tcp_z_m=-0.010),
        placement=PlacementSpec(mode="flat_lay", rack="upper"),
        coacd={"analytic": True},
    ),
}

ACTIVE_OBJECT = "mug"


def grasp_transform(spec: ObjectSpec) -> tuple[tuple, tuple]:
    """T_tcp_obj (pos, quat XYZW) for a spec, from its grasp family + measured dims.

    Derivations (documented per family; the mug case reproduces the frozen v0 transform):
      - Y-up ``rim_diam`` (mug): R = Rx(-90) maps z_tcp = -y_obj (upright carry, opening
        toward the gripper); the rim-center axis point (u, h/2, v) lands on (0, 0, rim_z).
      - Z-up ``rim_diam``/``rim_edge``: R = Rx(180) (z_tcp = -z_obj); rim center — or the rim
        wall point on the +y side (jaw axis) for ``rim_edge`` — lands on (0, 0, rim_z).
      - ``edge_pinch``: on-edge carry; the disc's rim point on +x_obj is the top of the
        vertical disc, radial direction up toward the wrist; pads close across the thickness
        (z_obj along the jaw axis y_tcp).
      - ``handle_pinch``: flat pick; pads across the handle width (y_obj), grasp point at
        ``grasp_point_m`` along the long axis.
    """
    fam = spec.grasp.family
    u, v = spec.body_center_uv
    r = spec.rim_radius_m
    z = spec.grasp.rim_tcp_z_m
    if spec.axis_obj == (0.0, 1.0, 0.0):  # legacy Y-up mug frame
        if fam != "rim_diam":
            raise ValueError(f"unsupported family {fam!r} for the legacy Y-up frame")
        # h2 from the bbox half along the axis (0.0407, the frozen v0 literal), NOT
        # height_m / 2 — the measured bbox is 0.1 mm asymmetric and the baseline cache hash
        # depends on the exact float. `+ 0.0` normalizes -0.0 for stable JSON hashing.
        h2 = spec.bbox_half[1]
        return (-u + 0.0, -v + 0.0, z + h2), (-0.70710678, 0.0, 0.0, 0.70710678)
    h2 = spec.bbox_half[2]
    if fam in ("rim_diam", "stem_pinch"):
        return (-u + 0.0, v + 0.0, z + h2), (1.0, 0.0, 0.0, 0.0)
    if fam == "rim_edge":
        return (-u + 0.0, v + r, z + h2), (1.0, 0.0, 0.0, 0.0)
    if fam == "edge_pinch":
        return (v + 0.0, 0.0, z + u + r), (-0.5, 0.5, 0.5, 0.5)
    if fam == "handle_pinch":
        # Rx(180): head (+x_obj) -> +x_tcp, the jaw-free direction (the Ry(180) variant
        # pointed the head into the wrist — measured 116 N at the scripts/setup/calibrate_grasp.py open gate)
        return (-spec.grasp.grasp_point_m + 0.0, 0.0, z), (1.0, 0.0, 0.0, 0.0)
    raise ValueError(f"unknown grasp family {fam!r}")


@contextlib.contextmanager
def active_object(name: str):
    """Temporarily activate an object class, restoring the previous one on exit.

    :func:`config_hash` — and therefore every cache-staleness check — is a function of the
    ACTIVE object, so reading a second class's collision cache requires activating it first. A
    multi-object episode has to touch several classes' caches during setup, and leaving the wrong
    one active afterwards would silently give the next grasp computation another object's
    geometry. Scoping the switch makes the read safe *and* keeps the staleness check honest,
    which a ``validate=False`` shortcut would not.

    Only valid after :mod:`dishsim.scene`/:mod:`dishsim.robots` are imported — those bind the
    object USD path at import time, so the pre-import activation rule still applies.

    Args:
        name: Object class to activate for the duration of the block.
    """
    previous = ACTIVE_OBJECT
    set_active_object(name)
    try:
        yield
    finally:
        set_active_object(previous)


def set_active_object(name: str) -> None:
    """Activate an object class by rewriting the active-object view in place.

    Must run before importing :mod:`dishsim.robots`/:mod:`dishsim.scene` (they bind the
    object USD path at import time) and before building collision caches.
    :func:`geometry.config_hash` reads these attributes at call time, so per-object caches
    invalidate correctly.

    Args:
        name: Key into :data:`OBJECTS`.
    """
    global ACTIVE_OBJECT, OBJECT_NAME, OBJECT_USD, OBJECT_MASS_KG, OBJECT_BBOX_HALF
    global OBJECT_AXIS_OBJ, OBJECT_BODY_CENTER_XZ, OBJECT_RIM_RADIUS_M, OBJECT_HEIGHT_M
    global GRASP_RIM_TCP_Z_M, GRASP_TCP_OBJ_POS, GRASP_TCP_OBJ_QUAT
    global GRIPPER_APERTURE_GRASP_RAD, GRIP_FORCE_MIN_N, GRIP_FORCE_MAX_N, GRIP_FORCE_EXEC_MAX_N
    global OBJECT_COUNTERTOP_POSES_W
    if name not in OBJECTS:
        raise ValueError(f"unknown object {name!r} (choices: {sorted(OBJECTS)})")
    spec = OBJECTS[name]
    ACTIVE_OBJECT = name
    OBJECT_NAME = spec.object_name
    OBJECT_USD = spec.usd_path
    OBJECT_MASS_KG = spec.mass_kg
    OBJECT_BBOX_HALF = spec.bbox_half
    OBJECT_AXIS_OBJ = spec.axis_obj
    OBJECT_BODY_CENTER_XZ = spec.body_center_uv
    OBJECT_RIM_RADIUS_M = spec.rim_radius_m
    OBJECT_HEIGHT_M = spec.height_m
    GRASP_RIM_TCP_Z_M = spec.grasp.rim_tcp_z_m
    GRASP_TCP_OBJ_POS, GRASP_TCP_OBJ_QUAT = grasp_transform(spec)
    # apertures/bands: calibrated values when frozen, else a linear-jaw estimate that only
    # gates FCL cluster prep (scripts/setup/calibrate_grasp.py must run before any demo trial trusts the pinch)
    if spec.grasp.aperture_rad is not None:
        GRIPPER_APERTURE_GRASP_RAD = spec.grasp.aperture_rad
    else:
        GRIPPER_APERTURE_GRASP_RAD = round(0.8 * (1.0 - spec.grasp.grasp_width_m / 0.085), 3)
    GRIP_FORCE_MIN_N = spec.grasp.force_min_n if spec.grasp.force_min_n is not None else 0.5
    GRIP_FORCE_MAX_N = spec.grasp.force_max_n if spec.grasp.force_max_n is not None else 20.0
    GRIP_FORCE_EXEC_MAX_N = (
        spec.grasp.force_exec_max_n if spec.grasp.force_exec_max_n is not None else 12.0
    )
    COACD["object"] = dict(spec.coacd)
    if spec.countertop_poses_w:
        OBJECT_COUNTERTOP_POSES_W = spec.countertop_poses_w


def active_object_spec() -> ObjectSpec:
    """The currently active :class:`ObjectSpec`."""
    return OBJECTS[ACTIVE_OBJECT]
SIM_DT = 1.0 / 60.0
