# Copyright (c) 2026, dishsim project.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Every tunable of the v0 placement pipeline, in one place.

Values marked *measured* come from ``docs/joint_report.md`` (regenerated by
``scripts/00_inspect_scene.py``) or from a ``scripts/10_v0_scene.py --measure`` run; do not
eyeball-edit them. Frame convention everywhere: **robot-base frame, meters, Z-up, quaternions
XYZW** (world frame = robot-base frame shifted by ``ROBOT_BASE_POS_W``; the robot base spawns
with identity rotation, asserted at scene build).

This module must stay importable without Kit *and* without the planning venv (numpy only).
"""

import math
import os

from . import ASSETS_DIR, PROJECT_ROOT

# ---------------------------------------------------------------------------------------------
# frame convention (asserted by scene.assert_frames and the collision-world manifest)
# ---------------------------------------------------------------------------------------------
FRAME_CONVENTION = {"frame": "robot_base", "units": "m", "up": "+z", "quat": "xyzw"}

# ---------------------------------------------------------------------------------------------
# scene layout (world frame; measured — docs/joint_report.md)
# ---------------------------------------------------------------------------------------------
ROBOT_BASE_POS_W = (0.0, 0.0, 0.25)
ROBOT_BASE_QUAT_W = (0.0, 0.0, 0.0, 1.0)
PEDESTAL_SIZE = (0.25, 0.25, 0.25)
PEDESTAL_POS_W = (0.0, 0.0, 0.125)
# dishwasher articulation-root (E_body_5) spawn pose: front face toward the robot, handle
# centered at x ~ 0.64 when the door is closed (measured RL placement, joint_report.md)
DISHWASHER_POS_W = (0.6498, 0.2423, 0.0)
DISHWASHER_QUAT_W = (0.0, 0.0, -0.70710678, 0.70710678)  # yaw -90 deg

ARM_JOINTS = [
    "shoulder_pan_joint",
    "shoulder_lift_joint",
    "elbow_joint",
    "wrist_1_joint",
    "wrist_2_joint",
    "wrist_3_joint",
]
HOME_Q = (0.0, -1.712, 1.712, -1.571, -1.571, 0.0)  # elbow-up home, faces +x (measured-stable)
UR5E_REACH_M = 0.85

# ---------------------------------------------------------------------------------------------
# static machine state (v0: door locked open, lower rack fully out)
# ---------------------------------------------------------------------------------------------
DOOR_OPEN_DEG = 90.0
DOOR_BAND_DEG = 5.0  # v0 USD clamps door limits to [open - band, open]
# The asset's effective mechanical stop is 89.05 deg (measured: the door rests there both under
# gravity and under +8 N*m in the joint_report door test, despite the authored 90 deg limit).
# Init at 89.0 so the settle transient is tiny; gravity presses the panel into the stop.
DOOR_INIT_RAD = math.radians(89.0)
DOOR_REST_DEG = 89.05  # measured rest angle at the stop
RACK_LOWER_EXT_M = -0.20  # PrismaticJoint_dishwasher_2_down: 0 = stowed, -0.2 = fully out
RACK_UPPER_EXT_M = -0.20  # baseline both_out: both racks fully extended
RACK_JOINT_TARGETS = {
    "PrismaticJoint_dishwasher_2_down": RACK_LOWER_EXT_M,
    "PrismaticJoint_dishwasher_2_up": RACK_UPPER_EXT_M,
}

# Rack-state scenarios — exactly the two real robot-facing INITIAL states (user-mandated).
# The dishwasher itself is unmodified (no rack raise): instead the robot does what a human
# does — it first RECONFIGURES the racks (rack_action: drive-synchronized pull/push on the
# named prismatic joint while the gripper visibly engages the rack's front handle), which
# brings BOTH scenarios to the same placement state (lower rack out, upper rack in — the
# geometry the placement pipeline is validated on), then picks the mug off the countertop
# and places it. "both_out" is the baseline (legacy assets/cache/, media/<phase>).
SCENARIOS = {
    "both_out": {  # both racks fully extended -> push the UPPER rack in, place into the lower
        "rack_lower_m": -0.20,
        "rack_upper_m": -0.20,
        "min_feasible_slots": 3,
        "rack_action": {
            "joint": "PrismaticJoint_dishwasher_2_up",
            "body": "E_shelf_03",
            "to": 0.0,
            "mode": "push",
        },
    },
    "both_in": {  # both racks fully retracted -> pull the LOWER rack out, place into it
        "rack_lower_m": 0.0,
        "rack_upper_m": 0.0,
        "min_feasible_slots": 3,
        "rack_action": {
            "joint": "PrismaticJoint_dishwasher_2_down",
            "body": "E_shelf_1_04",
            "to": -0.20,
            "mode": "pull",
        },
    },
}
SCENARIO_NAME = "both_out"  # active scenario; switch via apply_scenario() BEFORE scene imports

# The shared post-rack-action machine state every trial places in (lower out, upper in).
# Not a user-facing scenario — an internal state name usable with apply_scenario() and the
# cache/goal scripts (12-15) so pick/place planning has its own validated collision world.
PLACEMENT_STATE = "placement"
INTERNAL_STATES = {
    PLACEMENT_STATE: {"rack_lower_m": -0.20, "rack_upper_m": 0.0, "min_feasible_slots": 3},
}


def apply_scenario(name: str) -> None:
    """Activate a rack-state scenario (or internal machine state) by rewriting the rack
    targets in place.

    Must run before importing :mod:`dishsim.robots`/:mod:`dishsim.scene` (they bind rack
    values and the derived-USD path at import time). ``geometry.config_hash`` reads these
    attributes at call time, so per-state caches invalidate correctly.

    Args:
        name: Key into :data:`SCENARIOS` or :data:`INTERNAL_STATES` (e.g. ``"placement"``).
    """
    global RACK_LOWER_EXT_M, RACK_UPPER_EXT_M, RACK_JOINT_TARGETS, SCENARIO_NAME
    states = {**SCENARIOS, **INTERNAL_STATES}
    if name not in states:
        raise ValueError(f"unknown scenario {name!r} (choices: {sorted(states)})")
    sc = states[name]
    RACK_LOWER_EXT_M = sc["rack_lower_m"]
    RACK_UPPER_EXT_M = sc["rack_upper_m"]
    RACK_JOINT_TARGETS = {
        "PrismaticJoint_dishwasher_2_down": RACK_LOWER_EXT_M,
        "PrismaticJoint_dishwasher_2_up": RACK_UPPER_EXT_M,
    }
    SCENARIO_NAME = name


def state_params(name: str | None = None) -> dict:
    """Parameters of a scenario or internal machine state (e.g. Phase-E gates)."""
    name = name or SCENARIO_NAME
    return {**SCENARIOS, **INTERNAL_STATES}[name]


def scenario_cache_dir(name: str | None = None) -> str:
    """Collision-cache root for a scenario (baseline keeps the legacy ``assets/cache/``)."""
    name = name or SCENARIO_NAME
    if name == "both_out":
        return CACHE_DIR
    return os.path.join(ASSETS_DIR, "cache", "scenarios", name)


def scenario_media_dir(phase: str, name: str | None = None) -> str:
    """Media dir for a phase under the active scenario (baseline keeps ``media/<phase>``)."""
    name = name or SCENARIO_NAME
    base = os.path.join(PROJECT_ROOT, "media", phase)
    return base if name == "both_out" else os.path.join(base, name)

# ---------------------------------------------------------------------------------------------
# gripper (actuated between exactly two calibrated apertures: open at trial endpoints, grasp
# during all planned motion — matching the frozen-aperture FCL cluster)
# ---------------------------------------------------------------------------------------------
GRIPPER_JOINT = "finger_joint"  # 0 = open (85 mm), ~0.8 = closed (inverted vs Franka)
GRIPPER_APERTURE_OPEN_RAD = 0.0  # fully open — trial start and release
# Grasp aperture = theta_touch + delta, measured by `scripts/11_calibrate_grasp.py` (staircase
# ramp onto the welded mug: theta_touch is the first sustained pad contact, delta a small
# over-command chosen so the steady pad force lands mid-band; the finger drive's
# effort_limit_sim=10 caps the squeeze). Measured 2026-07-31 (PASS run, rim_z -0.020):
# theta_touch 0.055, steady pad force 5.14 N mean at this setting.
GRIPPER_APERTURE_GRASP_RAD: float | None = 0.058
# Mimic-consistent drive targets for the two stiff (k=10) `.*_inner_finger_joint` actuators:
# leaving their targets at 0 while finger_joint closes makes them fight the mimic constraint
# and contaminates the measured pad force. Signs are measured live by the calibration script
# (upstream gear-assembly pattern predicts left -1 / right +1; we freeze what the mimic
# actually settles to). None -> hold_targets falls back to target-follows-measured-position
# (zero spring torque, damping only). Measured 2026-07-31: mimic ratios -0.995 / +0.995.
GRIPPER_INNER_FINGER_SIGNS: dict[str, float] | None = {
    "left_inner_finger_joint": -1.0,
    "right_inner_finger_joint": 1.0,
}
GRIPPER_CLOSE_RAMP_STEPS = 90  # 1.5 s at SIM_DT — the on-camera close at trial start
GRIPPER_OPEN_RAMP_STEPS = 90  # the on-camera open before the weld releases

# ---------------------------------------------------------------------------------------------
# TCP frame (wrist_3_link -> TCP)
# ---------------------------------------------------------------------------------------------
# Measured live by `scripts/10_v0_scene.py --measure` (2026-07-29, PASS run): translation
# (0, 0.130, 0) — matches joint_report.md — and rotation (-0.5, -0.5, -0.5, 0.5) XYZW (an exact
# axis permutation; measured values deviated < 3e-8 from ideal and were snapped to it).
T_WRIST3_TCP_POS = (0.0, 0.130, 0.0)
T_WRIST3_TCP_QUAT: tuple[float, float, float, float] | None = (-0.5, -0.5, -0.5, 0.5)

# ---------------------------------------------------------------------------------------------
# carried object + grasp (defined ONCE, used by scene weld, FK attachment, goal generation)
# ---------------------------------------------------------------------------------------------
# YCB 029_plate does NOT exist in the Isaac 6.0 S3 bucket (HTTP 404, checked 2026-07-29), so the
# mug is the v0 stand-in, as the project brief allows.
OBJECT_NAME = "025_mug"
OBJECT_USD = os.path.join(ASSETS_DIR, "props", "025_mug_physics.usd")
OBJECT_MASS_KG = 0.118
# Measured from the mesh (2026-07-29): the "Axis_Aligned" asset lies ON ITS SIDE — the mug AXIS
# runs along OBJECT +Y (opening/rim at y = +0.0407, closed bottom at y = -0.0407), the handle
# points along +X, and the body circle in the xz-plane is centered at (x, z) = (-0.0110, 0.0)
# with outer radius 0.0399. Bbox: +-(0.0585, 0.0407, 0.0465), origin at bbox center.
OBJECT_BBOX_HALF = (0.0585, 0.0407, 0.0465)
OBJECT_AXIS_OBJ = (0.0, 1.0, 0.0)  # mug "up" (bottom -> opening) in the object frame
OBJECT_BODY_CENTER_XZ = (-0.0110, 0.0)
OBJECT_RIM_RADIUS_M = 0.0399
OBJECT_HEIGHT_M = 0.0813

# Carry pose ("grasp" transform): the mug rides UPRIGHT in a calibrated contact pinch — its
# rim band between the inner-finger pads, handle on the jaw-free axis, the hidden wrist weld
# still carrying the load. GRASP_RIM_TCP_Z_M places the rim plane along tool z relative to the
# TCP (positive = beyond the TCP, away from the wrist) so the pad contact patch presses the
# outer wall PAD_ENGAGEMENT_M below the rim edge. Measured by `scripts/11_calibrate_grasp.py`
# from the live pad map — do not eyeball.
# Historical (clearance-carry era, kept for the record): closing to 0.78 rad (jaw ~ a few mm)
# onto the ~80 mm mug drove the jaw sweep through the wall — measured 155-420 N pads-on-rim,
# 263 N with the rim 30 mm below the TCP (closed fingertips arc ~50+ mm past the TCP). The v0
# answer was to hang the mug 85 mm below the TCP, beyond any fingertip reach (0 N by
# construction). The pinch regime is different: the jaws stop AT the mug surface
# (jaw ~ 79.8 mm, theta ~ 0.05-0.15 rad), so the sweep never drives through the wall and the
# pad force is bounded by the calibrated band below.
# Derivation:
#   R: z_tcp = -y_obj (upright carry, opening toward the gripper), x_tcp = +x_obj  == Rx(-90)
#   t: rim-center axis point (-0.011, 0.0407, 0)_obj maps to (0, 0, GRASP_RIM_TCP_Z_M)_tcp
# Measured 2026-07-31 (scripts/11_calibrate_grasp.py PASS: zero contact at open, band held
# at hold, weld error 1.3 mm under load, forces vanish on open).
GRASP_RIM_TCP_Z_M: float | None = -0.0200
PAD_ENGAGEMENT_M = 0.012  # pad contact-patch center below the rim edge (design choice)
GRASP_TCP_OBJ_POS: tuple[float, float, float] | None = (
    None if GRASP_RIM_TCP_Z_M is None else (0.011, 0.0, GRASP_RIM_TCP_Z_M + 0.0407)
)
GRASP_TCP_OBJ_QUAT = (-0.70710678, 0.0, 0.0, 0.70710678)  # Rx(-90 deg), XYZW

# ---------------------------------------------------------------------------------------------
# grip contact gates (calibrated by scripts/11_calibrate_grasp.py, used by Phases C/D/F)
# ---------------------------------------------------------------------------------------------
# The object_contact sensor's filter list resolves per-partner forces; the two inner-finger
# pads are the only bodies allowed (required, in fact) to touch the carried mug while gripping.
GRIP_PAD_BODIES = ("left_inner_finger", "right_inner_finger")
# Steady per-pad pinch-force band [N] while holding still (frozen 2026-07-31 from the
# calibration force-vs-theta curve: steady 5.14 N mean, per-pad [2.47, 7.82] N — the mild
# asymmetry is the handle-side mass/gearing bias; band = steady/3 .. 3x steady).
GRIP_FORCE_MIN_N = 1.7
GRIP_FORCE_MAX_N = 15.4
# Dynamic per-pad allowance [N] during arm motion (frozen 2026-07-31: 10_v0_scene wiggle
# peak 8.03 N at +-0.25 rad wrist wiggle, x1.5 margin).
GRIP_FORCE_EXEC_MAX_N = 12.0
RETRACT_DIST_M = 0.08  # post-release tool-axis retract before the final evaluation window
# The placed mug settles up to ~6 mm off the release point while the withdrawing jaws have
# only ~2.6 mm/side clearance — a light brush during retract is physically expected (as in
# real loading). Below this, contact is recorded as a graze and the trial is judged by the
# final evaluation window; at or above it, the retract failed outright.
RETRACT_GRAZE_MAX_N = 2.0

# ---------------------------------------------------------------------------------------------
# cameras (world frame; FIXED across all phases so shots are comparable)
# ---------------------------------------------------------------------------------------------
CAMERA_HW = (720, 1280)
CAMERA_FPS = 30
CAMERAS = {
    # eye, target
    "front": ((-0.40, -0.80, 0.60), (0.60, 0.00, 0.15)),  # looking into the dishwasher opening
    "top": ((0.50, 0.01, 1.70), (0.50, 0.00, 0.10)),  # straight down over the extended rack
    "iso": ((-0.50, 1.10, 0.90), (0.50, 0.05, 0.22)),  # 3/4 view onto the opening, robot at right
}

# ---------------------------------------------------------------------------------------------
# Phase D — collision world
# ---------------------------------------------------------------------------------------------
CACHE_DIR = os.path.join(ASSETS_DIR, "cache")
COLLISION_MARGIN_M = 0.005  # hull inflation: the conservative-bias knob for FCL-vs-Isaac parity
# CoACD parameters per body (fallback key "default"); threshold is the concavity tolerance —
# lower = finer decomposition. The RACKS no longer go through CoACD: their meshes are generated
# by rack_gen from RACK_GEN below, and scripts/13 writes the generator's exact convex parts as
# the FCL pieces (zero decomposition slop on 3 mm wires). CoACD remains for the concave bodies
# whose geometry we don't control.
COACD = {
    "default": {"threshold": 0.05, "max_convex_hull": 32},
    "object": {"threshold": 0.03, "max_convex_hull": 32},  # keep the mug cavity open
}
CONTACT_FORCE_THRESH_N = 0.1  # Isaac ground-truth contact threshold for the parity check
# The robot base sits ON the pedestal by construction (permanent touching contact) and is
# bolted to the world — it can never produce a *new* collision. Excluded from both the Isaac
# ground truth and the FCL world checks, keeping the two sides mirror images.
PARITY_BODY_EXCLUDE = ["base_link"]
WORLD_CHECK_EXCLUDE = ["base_link"]

# ---------------------------------------------------------------------------------------------
# rack geometry generator (rack_gen) — single source of truth for BOTH replaced rack meshes.
# Design space = world-metric rack body frame: x = width, y = depth (y=0 the front edge, the
# end that extends toward the robot), z up from 0 at the lowest wire surface; meters.
# usd_prep authors these meshes into the derived v0 USD (replacing the ArtVIP flat baskets);
# scripts/13 writes the generator's convex parts as the FCL pieces. Vertical layout is derived:
# channel runners bottom at z=0, main runners raised by channel.drop, crossbars tangent on top
# (floor_top = crossbar top = the slot datum the Phase-E percentile must land on — everything
# floor-level therefore stays inside placement.py's 15 mm bottom-slab band).
# ---------------------------------------------------------------------------------------------
RACK_GEN_VERSION = 2  # v2: reference-appliance realism (Whirlpool WDTA50SAKZ / Bosch 800 /
#                       Frigidaire FDPC4314AS) — 3-gauge wires, 30 mm Whirlpool tine rows with
#                       candy-cane ends, fillets/ties/beads, fold-down insert row, wheels,
#                       front loading dip + handle, cup shelves, RackMatic blocks
RACK_GEN = {
    "E_shelf_1_04": {  # lower rack: rear plate bank + open zone (robot side) + bowl/slope side
        "usd_scale_x": 0.9191,  # authored x-scale on the body Xform (asserted at authoring)
        "footprint": (0.3663, 0.2868),  # world-space extents; == original basket footprint
        # 3-gauge hierarchy (real racks: frame >> runners > tines; real tine dia/pitch ~ 0.07)
        "wire_dia_heavy": 0.005,  # perimeter rails + the 2 outermost runners
        "wire_dia_load": 0.0036,  # depth-axis load runners
        "wire_dia_light": 0.0022,  # crossbars, tines, ribs, balusters, ties
        "wire_sides": 12,  # 12-gon: vertices exactly on -x/-y/-z -> exact assembled bounds
        # perimeter & rear guard: rear rim +29 % over the SIDE rails; the front rail dips for
        # loading clearance (Whirlpool/Bosch signature) with a center grab handle above it
        "rim_side_h": 0.045,
        "rim_front_h": 0.034,  # dipped front-rail height over front_dip_x
        # the loading dip spans the whole open zone (real racks run the low front rail across
        # the loading width) — it is also the mug's entry corridor under the raised upper rack
        "front_dip_x": (0.125, 0.340),
        "handle": {"x": (0.160, 0.210), "grip_z": 0.055},
        "rim_rear_h": 0.058,
        "rear_zone_y0": 0.190,  # where the raised rear-third side rails begin
        "corner_r": 0.016,
        "corner_segments": 4,
        "baluster_pitch": 0.035,
        "guard_mid_rail": True,  # retention mid rail halfway up the raised rear section
        # floor & zoned grid: open runner surface gaps 40 mm (real racks never exceed ~40);
        # one light dense runner per span midpoint under the bank -> 19 mm dense gaps
        "runner_xs": (0.029, 0.0725, 0.1160, 0.1595, 0.2065, 0.2501, 0.2937, 0.3373),
        "channel": {"x": (0.169, 0.197), "runner_xs": (0.176, 0.190), "drop": 0.004},
        "crossbar_ys": (0.025, 0.070, 0.115, 0.160),
        "slope_zones": ((0.004, 0.048),),  # drinkware ramp along the x=0 side wall
        "slope_deg": 6.0,
        "slope_sign": -1.0,  # floor descends toward the wall (mug leans into the wall)
        # rear plate bank: 12 tines/row at 30 mm pitch (11 slots — the Whirlpool W10728160
        # row pattern), rows 52 mm apart (true two-point plate support), +7 deg lean into the
        # guard; row ends are candy-cane hooks; straight tines get capped bead tips
        "plate_zone_y": (0.205, 0.285),
        "plate_rows_y": (0.220, 0.272),  # 0.212 would block the y=0.1434 slot columns (-6 mm)
        "plate_tine_pitch": 0.030,
        "plate_tine_xspan": (0.022, 0.352),
        "plate_tine_h": 0.070,
        "plate_tine_lean_deg": 7.0,
        "candy_cane": {"r": 0.012, "sweep_deg": 120.0, "segments": 4},
        "tine_fillet": {"r": 0.006, "segments": 3},  # U-bend fillet at every tine base
        "tine_tie_frac": 0.6,  # mid-height tie wire per row at 0.6 * tine height
        "tine_bead": {"dia_factor": 1.6, "len": 0.004},  # push-on tip caps (Frigidaire kit)
        # fold-down insert row (Bosch "flip tine, dark gray" / Whirlpool gray tine row): the
        # REAR row is a visually distinct second mesh — thicker spine, hinge bosses, stop clip
        "insert": {
            "row": 1,
            "spine_dia": 0.0055,
            "boss_dia": 0.009,
            "boss_len": 0.010,
            "clip_size": (0.012, 0.008, 0.008),
        },
        "bank_bar_ys": (0.197, 0.242, 0.280),
        # corrugated cradle ribs: V-profile under both tine rows, wavelength = tine pitch
        "rib_amplitude": 0.0025,
        # bowl tines: 42 mm high, 45 mm pitch, on the slope side
        "bowl_tine_xs": (0.055, 0.100),
        "bowl_tine_ys": (0.025, 0.070, 0.115, 0.160),
        "bowl_tine_h": 0.042,
        # roller wheels: 4, outer face exactly on the footprint plane, bottoms exactly z=0
        "wheels": {"dia": 0.022, "width": 0.008, "y_inset": 0.030},
        # open zone (flat floor, mug slots; drives the Phase-D probes + the Phase-E guarantee:
        # slot-grid columns x={0.1832, 0.2432} x y={0.0834, 0.1434} stay mug-clear by design)
        "open_zones": ((0.115, 0.360, 0.010, 0.190),),
        "mass_kg": 0.9,  # authored explicitly (deterministic vs auto-mass); horizontal joint
        "sdf_resolution": 768,  # 0.48 mm voxel -> ~4.6 across a 2.2 mm wire
    },
    "E_shelf_03": {  # upper rack: glass/mug variant — shelves, divider, no plate bank
        "usd_scale_x": 0.94,
        "footprint": (0.3747, 0.2868),
        "wire_dia_heavy": 0.005,
        "wire_dia_load": 0.0036,
        "wire_dia_light": 0.0022,
        "wire_sides": 12,
        "rim_side_h": 0.040,  # level front (no loading dip on the upper rack)
        "rim_front_h": 0.040,
        # front pull/push handle (real upper racks have one; the rack_action engages it)
        "handle": {"x": (0.160, 0.210), "grip_z": 0.060},
        "rim_rear_h": 0.050,  # +25 %
        "rear_zone_y0": 0.190,
        "corner_r": 0.016,
        "corner_segments": 4,
        "baluster_pitch": 0.035,
        "guard_mid_rail": True,
        "runner_xs": (0.030, 0.0736, 0.1172, 0.1608, 0.2044, 0.2480, 0.2916, 0.3352),  # 40 mm
        "crossbar_ys": (0.025, 0.070, 0.115, 0.160, 0.205, 0.250),  # 42 mm gaps
        "slope_zones": ((0.004, 0.048), (0.3267, 0.3707)),  # ramps along BOTH side walls
        "slope_deg": 6.0,
        "slope_sign": 1.0,  # ascends toward the wall (keeps wire bottoms above z=0)
        "divider_tine_x": 0.187,
        "divider_tine_ys": (0.025, 0.070, 0.115, 0.160, 0.205, 0.250),
        "divider_tine_h": 0.040,
        # fold-down cup shelves with stemware scallops, confined over the slope zones so the
        # mug strips stay clear (Bosch two cup shelves / Whirlpool push-up shelf)
        "cup_shelf": {
            "depth": 0.055,
            "y_span": (0.045, 0.135),
            "mount_z": 0.030,
            "tilt_deg": 13.0,
            "rungs": 5,
            "scallops": 3,
            "scallop_r": 0.008,
        },
        # Bosch RackMatic lever end caps on the outer side-rail faces (size = x, y, z extents)
        "rackmatic_blocks": {"size": (0.014, 0.026, 0.012), "ys": (0.060, 0.220), "z": 0.030},
        "wheels": {"dia": 0.022, "width": 0.008, "y_inset": 0.030},
        "open_zones": ((0.068, 0.182, 0.020, 0.180), (0.193, 0.307, 0.020, 0.180)),
        "mass_kg": 0.7,
        "sdf_resolution": 768,
    },
}

# ---------------------------------------------------------------------------------------------
# Phase E — placement goals
# ---------------------------------------------------------------------------------------------
SLOT_TOL_LATERAL_M = 0.015
SLOT_TOL_TILT_DEG = 10.0
GOAL_POSE_SAMPLES_PER_SLOT = 64
SETTLE_STEPS = 300  # success criterion: pose holds for this many physics steps after release
# Slot derivation (the ArtVIP lower rack is a shallow WIRE BASKET, not a plate-tine rack — the
# mug STANDS on the wire floor; a "slot" is a standing position on a grid). Slot centers form
# an overlapping candidate grid (one object placed per trial), spanning the basket from the
# protruding front to the deep interior — rear-slot infeasibility is expected signal.
SLOT_RIM_INSET_M = 0.055  # keep the mug footprint away from the basket rim walls
SLOT_GRID_PITCH_M = 0.06  # candidate-center spacing (overlap allowed)
RELEASE_HOVER_M = 0.012  # goal poses hover the object above the wire floor (> collision margin,
#                          small enough that the release drop is a non-event)

# ---------------------------------------------------------------------------------------------
# rack manipulation + countertop pick (the both_in / both_out trial choreography)
# ---------------------------------------------------------------------------------------------
# Countertop: the ArtVIP tub is open-topped in collision; freestanding dishwashers have a
# worktop. usd_prep authors this slab onto E_body_5 in the derived USDs — it is also the mug's
# initial resting surface. Shell top measured at world z 0.47, footprint x [0.65, 1.045],
# y [-0.24, 0.242].
COUNTERTOP_SIZE = (0.395, 0.482, 0.020)  # world-aligned box extents [m]
COUNTERTOP_CENTER_W = (0.8475, 0.001, 0.48)  # world center; top surface at z 0.49
# Mug initial pose: standing upright on the countertop at the robot-nearest corner (the wrist
# IK target lands at ~0.81 of the 0.85 m reach — verified with the analytic IK offline). Yaw
# orients the handle so the fixed calibrated grasp transform stays IK-reachable.
MUG_COUNTERTOP_POS_W = (0.665, -0.185, 0.5307)  # root (= bbox center); mug base at z 0.49
MUG_COUNTERTOP_YAW_DEG = 0.0
PICK_HOVER_M = 0.10  # planned pre-grasp TCP hover above the grasp pose; the descent is a
#                      scripted straight line gated by the calibrated pinch band, not FCL
#                      (the goal pose is inside the inflated-hull margin of the mug by design)
PICK_DESCEND_STEPS = 120
PICK_LIFT_M = 0.12  # straight lift after weld-on, before planning to the slot
# Rack slide: drive-synchronized manipulation — the gripper visibly engages the rack's front
# handle while the rack joint's drive target ramps to rack_action["to"] and the TCP tracks the
# moving handle (same visible-contact + guaranteed-actuation methodology as the mug weld).
RACK_SLIDE_STEPS = 240  # 4 s at SIM_DT for the 0.2 m travel
RACK_HANDLE_APERTURE_RAD = 0.70  # near-closed pinch around the 3.6 mm handle rod (pull)
RACK_PUSH_APERTURE_RAD = 0.78  # closed-fist contact for push
RACK_SLIDE_TOL_M = 0.005  # the rack must settle within this of the action target
RACK_TRACK_TOL_M = 0.020  # max TCP-vs-handle tracking error during the slide
RACK_APPROACH_HOVER_M = 0.08  # planned pre-engage TCP offset above/behind the handle

# ---------------------------------------------------------------------------------------------
# Phase F — planning + execution
# ---------------------------------------------------------------------------------------------
# Placement always happens in the reconfigured machine state (lower rack out, upper in — the
# rack_action runs first), so the planning problem matches the validated open-approach layout;
# the rack-approach and pick plans carry nothing and are easy. 20 s is generous headroom.
PLAN_TIME_BUDGET_S = 20.0
PLAN_RRT_RANGE_RAD = 0.5  # smaller extension steps handle the cluttered machine front reliably
GOALS_PER_PLAN = 64  # random goal-set subset handed to OMPL per trial
# planning bounds: full joint limits minus a small margin (config-tunable; tighten if RRT
# wanders into pointless windups)
PLAN_JOINT_BOUNDS_MARGIN_RAD = 0.05
PLAN_VALIDITY_RESOLUTION_RAD = 0.015
EXEC_JOINT_SPEED_RAD_S = 0.5  # constant joint-speed cap for time parameterization
SIM_DT = 1.0 / 60.0
