# Copyright (c) 2026, dishsim project.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Capacity + multi-object demo report (docs/capacity_report.md + figures).

Aggregates:
- the object library registry (sources, documented scale factors, dims, masses),
- per-class robot-demo trials (``results/demos/<object>/trial_*.json`` + the mug campaign),
- the capacity fill (``results/fill/capacity.json``).

Venv-side, no Kit: ``env_isaaclab/bin/python scripts/31_capacity_report.py``
"""

import glob
import json
import os
import shutil
import sys

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(PROJECT_ROOT, "src"))

from dishsim import config  # noqa: E402

FIG_DIR = os.path.join(PROJECT_ROOT, "docs", "figures")
REAL_DIMS = {  # source-asset real-world size [m] (YCB dataset dims; procedural = as designed)
    "mug": "80 dia x 81",
    "plate": "258 dia x 27",
    "saucer": "258 dia x 27",
    "bowl": "159 dia x 53",
    "cup": "57 dia x 62",
    "fork": "198 long",
    "spoon": "195 long",
    "knife": "215 long",
    "spatula": "311 long",
    "pitcher": "242 tall",
    "tumbler": "designed",
    "wine_glass": "designed",
    "serving_spoon": "designed",
    "container": "designed",
    "lid": "designed",
}


def load_demo_trials() -> list[dict]:
    trials = []
    for path in glob.glob(os.path.join(PROJECT_ROOT, "results", "**", "trial_*.json"), recursive=True):
        with open(path) as f:
            trials.append(json.load(f))
    return trials


def fmt_dims(spec) -> str:
    return " x ".join(f"{2 * h * 1000:.0f}" for h in spec.bbox_half)


def main() -> None:
    os.makedirs(FIG_DIR, exist_ok=True)
    trials = load_demo_trials()
    cap_path = os.path.join(PROJECT_ROOT, "results", "fill", "capacity.json")
    cap = json.load(open(cap_path)) if os.path.exists(cap_path) else None

    by_obj: dict[str, list[dict]] = {}
    for t in trials:
        by_obj.setdefault(t.get("object", "mug"), []).append(t)

    lines = []
    w = lines.append
    w("# Multi-Object Capacity Report\n")
    w("Generated by `scripts/31_capacity_report.py` from the trial JSONs and the capacity fill.\n")

    # ---- library table -----------------------------------------------------------------------
    w("## Object library (scale-to-fit)\n")
    w("The ArtVIP dishwasher is compact (lower rack 366 x 287 mm, 154 mm inter-rack")
    w("clearance, 30 mm tine pitch); sourced objects are scaled to rack-proportional size —")
    w("the documented factor below. Dims are measured from the built asset (scripts/03), not")
    w("eyeballed.\n")
    w("| object | source | scale | scaled dims [mm] | source real size [mm] | mass [kg] | grasp family | placement |")
    w("|---|---|---|---|---|---|---|---|")
    for name in sorted(config.OBJECTS):
        s = config.OBJECTS[name]
        src = {"isaac_ycb": f"Isaac YCB {s.source_id}", "ycb16k": f"YCB {s.source_id}",
               "procedural": "procedural"}[s.source]
        w(f"| {name} | {src} | {s.scale} | {fmt_dims(s)} | {REAL_DIMS.get(name, '-')} "
          f"| {s.mass_kg} | {s.grasp.family} | {s.placement.mode} ({s.placement.rack}) |")
    w("")

    # ---- robot demos -------------------------------------------------------------------------
    w("## Robot pick-and-place demos\n")
    w("One scene per class (`scripts/20 --object <name> --scenario placement`); the carried")
    w("object rides a calibrated contact pinch with the hidden wrist weld bearing the load")
    w("(edge-pinch discs start welded — grasp acquisition for flat-lying plates is out of")
    w("scope, as in v0). Every trial has an MP4 + final still under `media/F/`.\n")
    w("| object | trials | success | grasp aperture [rad] | steady pinch [N] | plan time [s] | failure stages |")
    w("|---|---|---|---|---|---|---|")
    demo_rows = []
    for name in sorted(by_obj):
        ts = by_obj[name]
        n_ok = sum(t["success"] for t in ts)
        spec = config.OBJECTS.get(name)
        ap = spec.grasp.aperture_rad if spec else None
        f_lo = spec.grasp.force_min_n if spec else None
        f_hi = spec.grasp.force_max_n if spec else None
        pinch = f"[{f_lo}, {f_hi}]" if f_lo is not None else "-"
        plans = [t["plan_time_s"] for t in ts if t.get("plan_time_s")]
        plan_s = f"{min(plans):.1f}-{max(plans):.1f}" if plans else "-"
        fails = sorted({t["failure_stage"] for t in ts if t["failure_stage"]})
        w(f"| {name} | {len(ts)} | {n_ok}/{len(ts)} | {ap if ap is not None else '-'} "
          f"| {pinch} | {plan_s} | {', '.join(fails) or '-'} |")
        demo_rows.append((name, n_ok, len(ts)))
    w("")

    # ---- capacity ----------------------------------------------------------------------------
    if cap:
        w("## Full-load capacity (physics fill)\n")
        w(f"Planned **{cap['n_planned']}** items from the deterministic fill plan")
        w(f"(`dishsim.fill_plan`, FCL-validated); **{cap['n_stable']}** settled stably.")
        closable = cap["closable"]
        w(f"Closability (motorized slide-in of both racks to the stowed position): "
          f"**{'CLOSABLE' if closable else 'NOT CLOSABLE'}** "
          f"(rack stow error {cap['rack_stow_err_m'] * 1000:.1f} mm, "
          f"{len(cap['displaced_on_close'])} item(s) displaced).\n")
        w("| object | planned | stable |")
        w("|---|---|---|")
        for name in sorted(cap["counts_planned"]):
            w(f"| {name} | {cap['counts_planned'][name]} | {cap['counts_stable'].get(name, 0)} |")
        w(f"| **total** | **{cap['n_planned']}** | **{cap['n_stable']}** |")
        w("")
        if cap["displaced_on_close"]:
            w("Displaced on slide-in: " + ", ".join(
                f"{d['item']} ({d['slip_mm']} mm / {d['rot_deg']} deg)" for d in cap["displaced_on_close"]) + "\n")
        unstable = [k for k, v in cap["items"].items() if not v["stable"]]
        if unstable:
            w("Unstable at fill (parked, honest capacity): " + ", ".join(unstable) + "\n")

    # ---- media gallery -----------------------------------------------------------------------
    w("## Media\n")
    w("| what | path |")
    w("|---|---|")
    if cap:
        for name, p in cap["media"]["stills"].items():
            w(f"| loaded machine ({name}) | `{p}` |")
        w(f"| fill timelapse | `{cap['media']['timelapse']}` |")
        w(f"| orbit clip | `{cap['media']['orbit']}` |")
    for name in sorted(by_obj):
        for t in by_obj[name]:
            if t.get("media", {}).get("video"):
                w(f"| {name} demo {t['trial']} | `{t['media']['video']}` |")
    w("| object library sheet | `media/assets/library_sheet.png` |")
    w("| per-class calibrations | `media/C2/<object>/` |")
    w("")

    # ---- figures -----------------------------------------------------------------------------
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        if cap:
            names = sorted(cap["counts_planned"])
            planned = [cap["counts_planned"][n] for n in names]
            stable = [cap["counts_stable"].get(n, 0) for n in names]
            fig, ax = plt.subplots(figsize=(9, 4))
            x = range(len(names))
            ax.bar(x, planned, width=0.6, color="#c9d7e4", label="planned")
            ax.bar(x, stable, width=0.6, color="#1a80bb", label="stable")
            ax.set_xticks(list(x))
            ax.set_xticklabels(names, rotation=45, ha="right")
            ax.set_ylabel("items")
            ax.set_title(f"Full-load capacity: {cap['n_stable']}/{cap['n_planned']} items stable"
                         f" — {'closable' if cap['closable'] else 'not closable'}")
            ax.legend()
            fig.tight_layout()
            fig.savefig(os.path.join(FIG_DIR, "capacity_by_class.png"), dpi=140)
            plt.close(fig)
            w("![capacity](figures/capacity_by_class.png)\n")
        if demo_rows:
            fig, ax = plt.subplots(figsize=(7, 3.2))
            names = [r[0] for r in demo_rows]
            rate = [r[1] / max(1, r[2]) for r in demo_rows]
            ax.bar(range(len(names)), rate, color="#1a80bb")
            ax.set_xticks(range(len(names)))
            ax.set_xticklabels(names, rotation=45, ha="right")
            ax.set_ylim(0, 1.05)
            ax.set_ylabel("success rate")
            ax.set_title("Robot demo success per object class")
            fig.tight_layout()
            fig.savefig(os.path.join(FIG_DIR, "demo_success_by_class.png"), dpi=140)
            plt.close(fig)
            w("![demos](figures/demo_success_by_class.png)\n")
    except ImportError:
        print("[WARN] matplotlib unavailable — figures skipped")

    # curated stills into docs/figures
    if cap:
        for name, p in cap["media"]["stills"].items():
            src = os.path.join(PROJECT_ROOT, p)
            if os.path.exists(src):
                shutil.copy(src, os.path.join(FIG_DIR, f"loaded_{name}.png"))

    out = os.path.join(PROJECT_ROOT, "docs", "capacity_report.md")
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"[INFO] wrote {out}")
    print("[RESULT] PASS")


if __name__ == "__main__":
    main()
