"""Current-asset validation and measured-pose collision queries for random trials.

USD, FCL and simulator modules are imported only when a live collision world is
constructed. The validation function can run on the host before launching Kit.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

import numpy as np


KINDS = ("dinner_plate", "bowl", "mug")


def _digest(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def _json_value(value):
    return json.loads(json.dumps(value))


def validate_inputs(usd_path):
    """Reject stale model geometry and tableware before an experiment starts.

    Catalog rack fields are checked for provenance, never used to restrict the
    rack on which a dish may be tested. Only the three tested dishes are needed.
    """
    from . import tableware
    from .asset import BODY_POSITIONS, COMPONENT_FILES, JOINT_LIMITS
    from .geometry import PARAMETERS

    usd_path = Path(usd_path).resolve()
    if usd_path.name != "fdpc4221as.usdc" or not usd_path.is_file():
        raise ValueError(f"Expected an existing fdpc4221as.usdc appliance: {usd_path}")
    directory = usd_path.parent
    parameter_path = directory / "parameters.json"
    report_path = directory / "geometry_validation.json"
    catalog_path = directory / "tableware/catalog.json"
    try:
        parameters = json.loads(parameter_path.read_text())
        report = json.loads(report_path.read_text())
        catalog = json.loads(catalog_path.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"Missing or unreadable current-asset metadata: {exc}") from exc
    for key, expected in (("geometry", PARAMETERS), ("body_positions_m", BODY_POSITIONS),
                          ("joint_limits_usd", JOINT_LIMITS)):
        if parameters.get(key) != _json_value(expected):
            raise ValueError(f"Stale parameters.{key}: rebuild the current Frigidaire asset")
    if not str(report.get("result", "")).startswith("PASS"):
        raise ValueError("USD authoring report did not pass")
    if set(report.get("components", {})) != set(COMPONENT_FILES):
        raise ValueError("USD authoring report does not describe all appliance components")
    for rack, parameter in (("LowerRack", "lower_rack"), ("UpperRack", "upper_rack")):
        if report["components"][rack].get("geometry_revision") != PARAMETERS[parameter]["geometry_revision"]:
            raise ValueError(f"Stale {rack} geometry revision")
    source_hash = _digest(tableware.__file__)
    if catalog.get("source_sha256") != source_hash:
        raise ValueError("Tableware catalog was generated by a different tableware source")
    hashes = report.get("sha256", {})
    required = [usd_path.name, *COMPONENT_FILES.values(), *(f"tableware/{kind}.usdc" for kind in KINDS)]
    actual = {}
    for name in required:
        path = directory / name
        if not path.is_file():
            raise ValueError(f"Required experiment asset missing: {path}")
        actual[name] = _digest(path)
        if hashes.get(name) != actual[name]:
            raise ValueError(f"USD authoring hash mismatch: {name}")
    for kind in KINDS:
        entry = catalog.get("items", {}).get(kind, {})
        if any(entry.get(key) != _json_value(value) for key, value in tableware.CATALOG[kind].items()):
            raise ValueError(f"Tableware catalog disagrees with current CATALOG: {kind}")
        if entry.get("sha256") != actual[f"tableware/{kind}.usdc"]:
            raise ValueError(f"Tableware catalog hash mismatch: {kind}")
    return {"asset_path": str(usd_path), "asset_hashes": actual,
            "parameters_sha256": _digest(parameter_path), "geometry_report_sha256": _digest(report_path),
            "catalog_sha256": _digest(catalog_path), "tableware_source_sha256": source_hash,
            "catalog": {kind: catalog["items"][kind] for kind in KINDS},
            "body_positions_m": parameters["body_positions_m"],
            "geometry_revisions": {rack: report["components"][rack]["geometry_revision"]
                                   for rack in ("LowerRack", "UpperRack")}}


def _pose(pose):
    """Read a world pose without assuming a quaternion convention at the boundary."""
    if isinstance(pose, dict):
        position = np.asarray(pose["position_m"], dtype=float)
        quaternion = np.asarray(pose["quaternion_xyzw"], dtype=float)
        if (position.shape != (3,) or quaternion.shape != (4,)
                or not np.isfinite(position).all() or not np.isfinite(quaternion).all()
                or abs(np.linalg.norm(quaternion) - 1.) > 1e-5):
            raise ValueError("World poses require finite positions and normalized XYZW quaternions")
        x, y, z, w = quaternion / np.linalg.norm(quaternion)
        rotation = np.array([[1-2*(y*y+z*z), 2*(x*y-z*w), 2*(x*z+y*w)],
                             [2*(x*y+z*w), 1-2*(x*x+z*z), 2*(y*z-x*w)],
                             [2*(x*z-y*w), 2*(y*z+x*w), 1-2*(x*x+y*y)]])
        return rotation, position
    matrix = np.asarray(pose, dtype=float)
    if (matrix.shape != (4, 4) or not np.isfinite(matrix).all()
            or not np.allclose(matrix[3], (0, 0, 0, 1), atol=1e-8)
            or not np.allclose(matrix[:3, :3].T @ matrix[:3, :3], np.eye(3), atol=1e-6)
            or not np.isclose(np.linalg.det(matrix[:3, :3]), 1., atol=1e-6)):
        raise ValueError("World pose must be a finite rigid 4x4 transform")
    return matrix[:3, :3], matrix[:3, 3]


class LiveCollisionWorld:
    """Actual authored colliders placed at measured component world transforms.

    All five appliance poses must be supplied before querying. The independent
    basket and rotating door are updated just like the articulated rack bodies.
    Candidate proxies are reused; no inflation or slot restrictions are added.
    """
    def __init__(self, asset_dir):
        import fcl
        from .asset import COMPONENT_FILES
        from .loading import CollisionWorld, collision_parts, visual_points

        self.fcl = fcl
        self._ready = False
        directory = Path(asset_dir)
        self.component_parts = {name: collision_parts(directory / filename)
                                for name, filename in COMPONENT_FILES.items()}
        self.component_objects = {name: CollisionWorld.transform(self, parts, np.eye(3), np.zeros(3))
                                  for name, parts in self.component_parts.items()}
        self.manager = fcl.DynamicAABBTreeCollisionManager()
        self.manager.registerObjects([obj for objects in self.component_objects.values() for obj in objects])
        self.manager.setup()
        self.parts = {kind: collision_parts(directory / "tableware" / f"{kind}.usdc") for kind in KINDS}
        self.points = {kind: visual_points(directory / "tableware" / f"{kind}.usdc") for kind in KINDS}
        self._candidates = {kind: CollisionWorld.transform(self, parts, np.eye(3), np.zeros(3))
                            for kind, parts in self.parts.items()}

    def _set(self, objects, parts, rotation, position):
        for obj, part in zip(objects, parts):
            obj.setTransform(self.fcl.Transform(rotation @ part.rotation, rotation @ part.translation + position))

    def update_components(self, poses):
        """Replace every static transform with the current measured body pose."""
        if set(poses) != set(self.component_parts):
            raise ValueError("Measured poses must contain exactly all five appliance components")
        parsed = {name: _pose(pose) for name, pose in poses.items()}
        for name, (rotation, position) in parsed.items():
            self._set(self.component_objects[name], self.component_parts[name], rotation, position)
        self.manager.update()
        self._ready = True

    def collides(self, kind, pose_world):
        """Whether the dish at a world pose intersects any measured component."""
        if not self._ready:
            raise RuntimeError("Update measured appliance component poses before querying collisions")
        if kind not in self.parts:
            raise ValueError(f"Unsupported experiment dish: {kind}")
        rotation, position = _pose(pose_world)
        self._set(self._candidates[kind], self.parts[kind], rotation, position)
        for obj in self._candidates[kind]:
            data = self.fcl.CollisionData(request=self.fcl.CollisionRequest(num_max_contacts=1))
            self.manager.collide(obj, data, self.fcl.defaultCollisionCallback)
            if data.result.is_collision:
                return True
        return False
